# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'train_plag_model_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrainPlagModelWindow(object):
    def setupUi(self, TrainPlagModelWindow):
        TrainPlagModelWindow.setObjectName("TrainPlagModelWindow")
        TrainPlagModelWindow.resize(860, 598)
        self.centralwidget = QtWidgets.QWidget(TrainPlagModelWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundImg = QtWidgets.QLabel(self.centralwidget)
        self.backgroundImg.setGeometry(QtCore.QRect(0, 0, 860, 600))
        self.backgroundImg.setText("")
        self.backgroundImg.setPixmap(QtGui.QPixmap("resources/background.jpg"))
        self.backgroundImg.setScaledContents(True)
        self.backgroundImg.setObjectName("backgroundImg")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(30, 0, 800, 570))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"                    ")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.trainBtn = QtWidgets.QPushButton(self.groupBox)
        self.trainBtn.setEnabled(True)
        self.trainBtn.setGeometry(QtCore.QRect(530, 479, 240, 60))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.trainBtn.setFont(font)
        self.trainBtn.setAcceptDrops(False)
        self.trainBtn.setAutoFillBackground(False)
        self.trainBtn.setStyleSheet("\n"
"                            background-color: rgb(0, 0, 20);\n"
"                            font: 75 16pt \"Sitka Small\";\n"
"                            color: rgb(255, 255, 255);\n"
"                            border-width: 3px;\n"
"                            border-radius: 30px;\n"
"                            border-color: rgb(255, 255, 255);\n"
"                            border-style: solid;\n"
"                        ")
        self.trainBtn.setCheckable(False)
        self.trainBtn.setAutoDefault(False)
        self.trainBtn.setDefault(False)
        self.trainBtn.setFlat(False)
        self.trainBtn.setObjectName("trainBtn")
        self.backBtn = QtWidgets.QPushButton(self.groupBox)
        self.backBtn.setEnabled(True)
        self.backBtn.setGeometry(QtCore.QRect(30, 479, 240, 60))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.backBtn.setFont(font)
        self.backBtn.setAcceptDrops(False)
        self.backBtn.setAutoFillBackground(False)
        self.backBtn.setStyleSheet("\n"
"                            background-color: rgb(159, 0, 0);\n"
"                            font: 75 16pt \"Sitka Small\";\n"
"                            color: rgb(255, 255, 255);\n"
"                            border-width: 3px;\n"
"                            border-radius: 30px;\n"
"                            border-color: rgb(255, 255, 255);\n"
"                            border-style: solid;\n"
"                        ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/My Documents/Studies/Semester_9/פרויקט מסכם - שלב\n"
"                                ב/icons/pnghut_arrow-icon-direction-left-logo-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backBtn.setIcon(icon)
        self.backBtn.setIconSize(QtCore.QSize(24, 24))
        self.backBtn.setCheckable(False)
        self.backBtn.setAutoDefault(False)
        self.backBtn.setDefault(False)
        self.backBtn.setFlat(False)
        self.backBtn.setObjectName("backBtn")
        self.verticalFrame1 = QtWidgets.QFrame(self.groupBox)
        self.verticalFrame1.setGeometry(QtCore.QRect(30, 265, 450, 200))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.verticalFrame1.setFont(font)
        self.verticalFrame1.setAutoFillBackground(False)
        self.verticalFrame1.setStyleSheet("border-width: 3px;\n"
"                            border-radius: 15px;\n"
"                            border-color: rgb(0, 0, 0);\n"
"                            border-style: solid;\n"
"                            font: 8pt \"Sitka Small\";\n"
"                            color: rgb(255, 255, 255);\n"
"                            background-color: qlineargradient(spread:pad, x1:0.996, y1:0.0340909, x2:1, y2:0, stop:1\n"
"                            rgba(0, 0, 32, 170));\n"
"                        ")
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalGroupBox13 = QtWidgets.QGroupBox(self.verticalFrame1)
        self.verticalGroupBox13.setStyleSheet("border-width: 2px;\n"
"font: 10pt \"Sitka Small\";")
        self.verticalGroupBox13.setObjectName("verticalGroupBox13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalGroupBox13)
        self.verticalLayout_6.setContentsMargins(5, 36, 5, 18)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label1311 = QtWidgets.QLabel(self.verticalGroupBox13)
        self.label1311.setStyleSheet("border-width: 0px;\n"
"font: 8pt \"Sitka Small\";")
        self.label1311.setObjectName("label1311")
        self.verticalLayout_6.addWidget(self.label1311)
        self.horizontalLayout131 = QtWidgets.QHBoxLayout()
        self.horizontalLayout131.setObjectName("horizontalLayout131")
        self.path1312 = QtWidgets.QLineEdit(self.verticalGroupBox13)
        self.path1312.setStyleSheet("border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                            background-color: rgb(188, 188, 188);\n"
"                                                            color: rgb(0, 0, 0);\n"
"                                                        ")
        self.path1312.setObjectName("path1312")
        self.horizontalLayout131.addWidget(self.path1312)
        self.uploadBtn1313 = QtWidgets.QToolButton(self.verticalGroupBox13)
        self.uploadBtn1313.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadBtn1313.setMouseTracking(False)
        self.uploadBtn1313.setAutoFillBackground(False)
        self.uploadBtn1313.setStyleSheet("background-color: rgb(212, 212, 212);\n"
"                                                            border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                        ")
        self.uploadBtn1313.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/upload_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uploadBtn1313.setIcon(icon1)
        self.uploadBtn1313.setObjectName("uploadBtn1313")
        self.horizontalLayout131.addWidget(self.uploadBtn1313)
        self.verticalLayout_6.addLayout(self.horizontalLayout131)
        self.label1331 = QtWidgets.QLabel(self.verticalGroupBox13)
        self.label1331.setStyleSheet("border-width: 0px;\n"
"font: 8pt \"Sitka Small\";")
        self.label1331.setObjectName("label1331")
        self.verticalLayout_6.addWidget(self.label1331)
        self.horizontalLayout133 = QtWidgets.QHBoxLayout()
        self.horizontalLayout133.setObjectName("horizontalLayout133")
        self.seperator1333 = QtWidgets.QLineEdit(self.verticalGroupBox13)
        self.seperator1333.setStyleSheet("border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                            background-color: rgb(188, 188, 188);\n"
"                                                            color: rgb(0, 0, 0);\n"
"                                                        ")
        self.seperator1333.setObjectName("seperator1333")
        self.horizontalLayout133.addWidget(self.seperator1333)
        self.questionBtn1332 = QtWidgets.QToolButton(self.verticalGroupBox13)
        self.questionBtn1332.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn1332.setMouseTracking(False)
        self.questionBtn1332.setAutoFillBackground(False)
        self.questionBtn1332.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"                                                            background-color: rgb(0, 0, 50);\n"
"                                                            border-width: 1px;\n"
"                                                            border-radius: 14px;\n"
"                                                            border-color: rgb(255, 255, 255);\n"
"                                                            border-style: solid;\n"
"                                                        ")
        self.questionBtn1332.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/question_icon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.questionBtn1332.setIcon(icon2)
        self.questionBtn1332.setObjectName("questionBtn1332")
        self.horizontalLayout133.addWidget(self.questionBtn1332)
        self.verticalLayout_6.addLayout(self.horizontalLayout133)
        self.verticalLayout.addWidget(self.verticalGroupBox13)
        self.verticalGroupBox14 = QtWidgets.QGroupBox(self.verticalFrame1)
        self.verticalGroupBox14.setStyleSheet("\n"
"font: 10pt \"Sitka Small\";")
        self.verticalGroupBox14.setObjectName("verticalGroupBox14")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalGroupBox14)
        self.verticalLayout_7.setContentsMargins(5, 36, 5, 36)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label1411 = QtWidgets.QLabel(self.verticalGroupBox14)
        self.label1411.setStyleSheet("border-width: 0px;\n"
"font: 8pt \"Sitka Small\";\n"
"")
        self.label1411.setObjectName("label1411")
        self.verticalLayout_7.addWidget(self.label1411)
        self.horizontalLayout141 = QtWidgets.QHBoxLayout()
        self.horizontalLayout141.setContentsMargins(-1, 8, -1, 8)
        self.horizontalLayout141.setSpacing(10)
        self.horizontalLayout141.setObjectName("horizontalLayout141")
        self.path1412 = QtWidgets.QLineEdit(self.verticalGroupBox14)
        self.path1412.setStyleSheet("border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                            background-color: rgb(188, 188, 188);\n"
"                                                            color: rgb(0, 0, 0);\n"
"                                                        ")
        self.path1412.setObjectName("path1412")
        self.horizontalLayout141.addWidget(self.path1412)
        self.uploadBtn1413 = QtWidgets.QToolButton(self.verticalGroupBox14)
        self.uploadBtn1413.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadBtn1413.setMouseTracking(False)
        self.uploadBtn1413.setAutoFillBackground(False)
        self.uploadBtn1413.setStyleSheet("background-color: rgb(212, 212, 212);\n"
"                                                            border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                        ")
        self.uploadBtn1413.setText("")
        self.uploadBtn1413.setIcon(icon1)
        self.uploadBtn1413.setObjectName("uploadBtn1413")
        self.horizontalLayout141.addWidget(self.uploadBtn1413)
        self.verticalLayout_7.addLayout(self.horizontalLayout141)
        self.verticalLayout.addWidget(self.verticalGroupBox14)
        self.errorMsg = QtWidgets.QLabel(self.groupBox)
        self.errorMsg.setGeometry(QtCore.QRect(490, 420, 81, 41))
        self.errorMsg.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.errorMsg.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.983, y1:0.00568182,\n"
"                            x2:0.996, y2:0, stop:1 rgba(48, 48, 48, 143));\n"
"                            color: rgb(170, 0, 0);\n"
"                            font: 75 8pt \"System\";\n"
"                            border-radius: 10px;\n"
"                            border-style: solid;\n"
"                            border-width: 0px\n"
"                        ")
        self.errorMsg.setObjectName("errorMsg")
        self.verticalFrame2 = QtWidgets.QFrame(self.groupBox)
        self.verticalFrame2.setGeometry(QtCore.QRect(30, 100, 501, 161))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.verticalFrame2.setFont(font)
        self.verticalFrame2.setAutoFillBackground(False)
        self.verticalFrame2.setStyleSheet("border-width: 3px;\n"
"                            border-radius: 15px;\n"
"                            border-color: rgb(0, 0, 0);\n"
"                            border-style: solid;\n"
"                            font: 8pt \"Sitka Small\";\n"
"                            color: rgb(255, 255, 255);\n"
"                            background-color: qlineargradient(spread:pad, x1:0.996, y1:0.0340909, x2:1, y2:0, stop:1\n"
"                            rgba(0, 0, 32, 170));\n"
"                        ")
        self.verticalFrame2.setObjectName("verticalFrame2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame2)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalGroupBox11 = QtWidgets.QGroupBox(self.verticalFrame2)
        self.verticalGroupBox11.setStyleSheet("border-width: 2px;\n"
"font: 10pt \"Sitka Small\";\n"
"")
        self.verticalGroupBox11.setObjectName("verticalGroupBox11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox11)
        self.verticalLayout_2.setContentsMargins(5, 36, 5, 18)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout112 = QtWidgets.QHBoxLayout()
        self.horizontalLayout112.setObjectName("horizontalLayout112")
        self.radioButton1122 = QtWidgets.QRadioButton(self.verticalGroupBox11)
        self.radioButton1122.setStyleSheet("\n"
"font: 8pt \"Sitka Small\";")
        self.radioButton1122.setChecked(True)
        self.radioButton1122.setObjectName("radioButton1122")
        self.horizontalLayout112.addWidget(self.radioButton1122)
        self.verticalLayout_2.addLayout(self.horizontalLayout112)
        self.horizontalLayout113 = QtWidgets.QHBoxLayout()
        self.horizontalLayout113.setObjectName("horizontalLayout113")
        self.radioButton1132 = QtWidgets.QRadioButton(self.verticalGroupBox11)
        self.radioButton1132.setStyleSheet("\n"
"font: 8pt \"Sitka Small\";")
        self.radioButton1132.setObjectName("radioButton1132")
        self.horizontalLayout113.addWidget(self.radioButton1132)
        self.verticalLayout_2.addLayout(self.horizontalLayout113)
        self.verticalLayout_3.addWidget(self.verticalGroupBox11)
        self.verticalFrame1_2 = QtWidgets.QFrame(self.groupBox)
        self.verticalFrame1_2.setGeometry(QtCore.QRect(490, 265, 281, 141))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.verticalFrame1_2.setFont(font)
        self.verticalFrame1_2.setAutoFillBackground(False)
        self.verticalFrame1_2.setStyleSheet("border-width: 3px;\n"
"                            border-radius: 15px;\n"
"                            border-color: rgb(0, 0, 0);\n"
"                            border-style: solid;\n"
"                            font: 8pt \"Sitka Small\";\n"
"                            color: rgb(255, 255, 255);\n"
"                            background-color: qlineargradient(spread:pad, x1:0.996, y1:0.0340909, x2:1, y2:0, stop:1\n"
"                            rgba(0, 0, 32, 170));\n"
"                        ")
        self.verticalFrame1_2.setObjectName("verticalFrame1_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame1_2)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalGroupBox21 = QtWidgets.QGroupBox(self.verticalFrame1_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox21.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox21.setSizePolicy(sizePolicy)
        self.horizontalGroupBox21.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalGroupBox21.setStyleSheet("border-width: 2px;\n"
"font: 10pt \"Sitka Small\";")
        self.horizontalGroupBox21.setObjectName("horizontalGroupBox21")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox21)
        self.horizontalLayout_3.setContentsMargins(5, 36, 5, 18)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.authorName211 = QtWidgets.QLineEdit(self.horizontalGroupBox21)
        self.authorName211.setStyleSheet("border-width: 3px;\n"
"                                                    border-radius: 5px;\n"
"                                                    border-color: rgb(0, 0, 0);\n"
"                                                    border-style: solid;\n"
"                                                    background-color: rgb(188, 188, 188);\n"
"                                                    color: rgb(0, 0, 0);\n"
"                                                \n"
"")
        self.authorName211.setObjectName("authorName211")
        self.horizontalLayout_3.addWidget(self.authorName211)
        self.verticalLayout_4.addWidget(self.horizontalGroupBox21)
        TrainPlagModelWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TrainPlagModelWindow)
        QtCore.QMetaObject.connectSlotsByName(TrainPlagModelWindow)

    def retranslateUi(self, TrainPlagModelWindow):
        _translate = QtCore.QCoreApplication.translate
        TrainPlagModelWindow.setWindowTitle(_translate("TrainPlagModelWindow", "Train New Plagiarism Model"))
        self.groupBox.setTitle(_translate("TrainPlagModelWindow", "Train a new Model"))
        self.trainBtn.setText(_translate("TrainPlagModelWindow", "Train"))
        self.backBtn.setText(_translate("TrainPlagModelWindow", "Back"))
        self.verticalGroupBox13.setTitle(_translate("TrainPlagModelWindow", "Upload text file:"))
        self.label1311.setText(_translate("TrainPlagModelWindow", "Path to file (.txt) with books or excerpts of books:"))
        self.label1331.setText(_translate("TrainPlagModelWindow", "Seperator:"))
        self.verticalGroupBox14.setTitle(_translate("TrainPlagModelWindow", "Upload folder:"))
        self.label1411.setText(_translate("TrainPlagModelWindow", "Path to directory with books (.txt files):"))
        self.errorMsg.setText(_translate("TrainPlagModelWindow", "warning"))
        self.verticalGroupBox11.setTitle(_translate("TrainPlagModelWindow", "Choose a relevant format of your DB:"))
        self.radioButton1122.setText(_translate("TrainPlagModelWindow", "A text file containing books or excerpts of books"))
        self.radioButton1132.setText(_translate("TrainPlagModelWindow", "A folder containing books in text file format"))
        self.horizontalGroupBox21.setTitle(_translate("TrainPlagModelWindow", "Author name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TrainPlagModelWindow = QtWidgets.QMainWindow()
    ui = Ui_TrainPlagModelWindow()
    ui.setupUi(TrainPlagModelWindow)
    TrainPlagModelWindow.show()
    sys.exit(app.exec_())
