# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'train_model_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrainModelWindow(object):
    def setupUi(self, TrainModelWindow):
        TrainModelWindow.setObjectName("TrainModelWindow")
        TrainModelWindow.resize(860, 598)
        self.centralwidget = QtWidgets.QWidget(TrainModelWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundImg = QtWidgets.QLabel(self.centralwidget)
        self.backgroundImg.setGeometry(QtCore.QRect(0, 0, 860, 600))
        self.backgroundImg.setText("")
        self.backgroundImg.setPixmap(QtGui.QPixmap(
            "resources/background.jpg"))
        self.backgroundImg.setScaledContents(True)
        self.backgroundImg.setObjectName("backgroundImg")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(30, 0, 800, 570))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.trainBtn = QtWidgets.QPushButton(self.groupBox)
        self.trainBtn.setEnabled(True)
        self.trainBtn.setGeometry(QtCore.QRect(530, 479, 240, 60))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.trainBtn.setFont(font)
        self.trainBtn.setAcceptDrops(False)
        self.trainBtn.setAutoFillBackground(False)
        self.trainBtn.setStyleSheet("\n"
                                    "background-color: rgb(0, 0, 20);\n"
                                    "font: 75 16pt \"Sitka Small\";\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "border-width: 3px;\n"
                                    "border-radius: 30px;\n"
                                    "border-color: rgb(255, 255, 255);\n"
                                    "border-style: solid;")
        self.trainBtn.setCheckable(False)
        self.trainBtn.setAutoDefault(False)
        self.trainBtn.setDefault(False)
        self.trainBtn.setFlat(False)
        self.trainBtn.setObjectName("trainBtn")
        self.backBtn = QtWidgets.QPushButton(self.groupBox)
        self.backBtn.setEnabled(True)
        self.backBtn.setGeometry(QtCore.QRect(30, 479, 240, 60))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.backBtn.setFont(font)
        self.backBtn.setAcceptDrops(False)
        self.backBtn.setAutoFillBackground(False)
        self.backBtn.setStyleSheet("\n"
                                   "background-color: rgb(159, 0, 0);\n"
                                   "font: 75 16pt \"Sitka Small\";\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "border-width: 3px;\n"
                                   "border-radius: 30px;\n"
                                   "border-color: rgb(255, 255, 255);\n"
                                   "border-style: solid;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(
            "resources/left_arrow_icon.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backBtn.setIcon(icon)
        self.backBtn.setIconSize(QtCore.QSize(24, 24))
        self.backBtn.setCheckable(False)
        self.backBtn.setAutoDefault(False)
        self.backBtn.setDefault(False)
        self.backBtn.setFlat(False)
        self.backBtn.setObjectName("backBtn")
        self.verticalFrame1 = QtWidgets.QFrame(self.groupBox)
        self.verticalFrame1.setGeometry(QtCore.QRect(340, 100, 440, 370))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.verticalFrame1.setFont(font)
        self.verticalFrame1.setAutoFillBackground(False)
        self.verticalFrame1.setStyleSheet("border-width: 3px;\n"
                                          "border-radius: 15px;\n"
                                          "border-color: rgb(0, 0, 0);\n"
                                          "border-style: solid;\n"
                                          "font: 8pt \"Sitka Small\";\n"
                                          "color: rgb(255, 255, 255);\n"
                                          "background-color: qlineargradient(spread:pad, x1:0.996, y1:0.0340909, x2:1, y2:0, stop:1 rgba(0, 0, 32, 170));")
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalGroupBox11 = QtWidgets.QGroupBox(self.verticalFrame1)
        self.verticalGroupBox11.setObjectName("verticalGroupBox11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox11)
        self.verticalLayout_2.setContentsMargins(10, 24, 10, 12)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout111 = QtWidgets.QHBoxLayout()
        self.horizontalLayout111.setObjectName("horizontalLayout111")
        self.radioButton1112 = QtWidgets.QRadioButton(self.verticalGroupBox11)
        self.radioButton1112.setAutoFillBackground(False)
        self.radioButton1112.setChecked(True)
        self.radioButton1112.setObjectName("radioButton1112")
        self.horizontalLayout111.addWidget(self.radioButton1112)
        self.questionBtn1111 = QtWidgets.QToolButton(self.verticalGroupBox11)
        self.questionBtn1111.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn1111.setMouseTracking(False)
        self.questionBtn1111.setAutoFillBackground(False)
        self.questionBtn1111.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                           "background-color: rgb(0, 0, 50);\n"
                                           "border-width: 1px;\n"
                                           "border-radius: 14px;\n"
                                           "border-color: rgb(255, 255, 255);\n"
                                           "border-style: solid;")
        self.questionBtn1111.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/question_icon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.questionBtn1111.setIcon(icon1)
        self.questionBtn1111.setObjectName("questionBtn1111")
        self.horizontalLayout111.addWidget(self.questionBtn1111)
        self.verticalLayout_2.addLayout(self.horizontalLayout111)
        self.horizontalLayout112 = QtWidgets.QHBoxLayout()
        self.horizontalLayout112.setObjectName("horizontalLayout112")
        self.radioButton1122 = QtWidgets.QRadioButton(self.verticalGroupBox11)
        self.radioButton1122.setObjectName("radioButton1122")
        self.horizontalLayout112.addWidget(self.radioButton1122)
        self.questionBtn1121 = QtWidgets.QToolButton(self.verticalGroupBox11)
        self.questionBtn1121.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn1121.setMouseTracking(False)
        self.questionBtn1121.setAutoFillBackground(False)
        self.questionBtn1121.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                           "background-color: rgb(0, 0, 50);\n"
                                           "border-width: 1px;\n"
                                           "border-radius: 14px;\n"
                                           "border-color: rgb(255, 255, 255);\n"
                                           "border-style: solid;")
        self.questionBtn1121.setText("")
        self.questionBtn1121.setIcon(icon1)
        self.questionBtn1121.setObjectName("questionBtn1121")
        self.horizontalLayout112.addWidget(self.questionBtn1121)
        self.verticalLayout_2.addLayout(self.horizontalLayout112)
        self.horizontalLayout113 = QtWidgets.QHBoxLayout()
        self.horizontalLayout113.setObjectName("horizontalLayout113")
        self.radioButton1132 = QtWidgets.QRadioButton(self.verticalGroupBox11)
        self.radioButton1132.setObjectName("radioButton1132")
        self.horizontalLayout113.addWidget(self.radioButton1132)
        self.questionBtn1131 = QtWidgets.QToolButton(self.verticalGroupBox11)
        self.questionBtn1131.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn1131.setMouseTracking(False)
        self.questionBtn1131.setAutoFillBackground(False)
        self.questionBtn1131.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                           "background-color: rgb(0, 0, 50);\n"
                                           "border-width: 1px;\n"
                                           "border-radius: 14px;\n"
                                           "border-color: rgb(255, 255, 255);\n"
                                           "border-style: solid;")
        self.questionBtn1131.setText("")
        self.questionBtn1131.setIcon(icon1)
        self.questionBtn1131.setObjectName("questionBtn1131")
        self.horizontalLayout113.addWidget(self.questionBtn1131)
        self.verticalLayout_2.addLayout(self.horizontalLayout113)
        self.verticalLayout.addWidget(self.verticalGroupBox11)
        self.verticalGroupBox12_1 = QtWidgets.QGroupBox(self.verticalFrame1)
        self.verticalGroupBox12_1.setObjectName("verticalGroupBox12_1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalGroupBox12_1)
        self.verticalLayout_5.setContentsMargins(10, 24, 10, 12)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout121_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout121_1.setObjectName("horizontalLayout121_1")
        self.path_1 = QtWidgets.QLineEdit(self.verticalGroupBox12_1)
        self.path_1.setStyleSheet("border-width: 3px;\n"
                                  "border-radius: 5px;\n"
                                  "border-color: rgb(0, 0, 0);\n"
                                  "border-style: solid;\n"
                                  "background-color: rgb(188, 188, 188);\n"
                                  "color: rgb(0, 0, 0);")
        self.path_1.setObjectName("path_1")
        self.horizontalLayout121_1.addWidget(self.path_1)
        self.uploadBtn_1 = QtWidgets.QToolButton(self.verticalGroupBox12_1)
        self.uploadBtn_1.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadBtn_1.setMouseTracking(False)
        self.uploadBtn_1.setAutoFillBackground(False)
        self.uploadBtn_1.setStyleSheet("background-color: rgb(212, 212, 212);\n"
                                       "border-width: 3px;\n"
                                       "border-radius: 5px;\n"
                                       "border-color: rgb(0, 0, 0);\n"
                                       "border-style: solid;")
        self.uploadBtn_1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/upload_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uploadBtn_1.setIcon(icon2)
        self.uploadBtn_1.setObjectName("uploadBtn_1")
        self.horizontalLayout121_1.addWidget(self.uploadBtn_1)
        self.verticalLayout_5.addLayout(self.horizontalLayout121_1)
        self.horizontalLayout122_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout122_1.setContentsMargins(-1, 16, -1, 16)
        self.horizontalLayout122_1.setObjectName("horizontalLayout122_1")
        self.label1_1 = QtWidgets.QLabel(self.verticalGroupBox12_1)
        self.label1_1.setObjectName("label1_1")
        self.horizontalLayout122_1.addWidget(self.label1_1)
        self.columnName_1 = QtWidgets.QTextEdit(self.verticalGroupBox12_1)
        self.columnName_1.setStyleSheet("border-width: 3px;\n"
                                        "border-radius: 5px;\n"
                                        "border-color: rgb(0, 0, 0);\n"
                                        "border-style: solid;\n"
                                        "background-color: rgb(188, 188, 188);\n"
                                        "color: rgb(0, 0, 0);")
        self.columnName_1.setObjectName("columnName_1")
        self.horizontalLayout122_1.addWidget(self.columnName_1)
        self.questionBtn1221_1 = QtWidgets.QToolButton(self.verticalGroupBox12_1)
        self.questionBtn1221_1.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn1221_1.setMouseTracking(False)
        self.questionBtn1221_1.setAutoFillBackground(False)
        self.questionBtn1221_1.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                             "background-color: rgb(0, 0, 50);\n"
                                             "border-width: 1px;\n"
                                             "border-radius: 14px;\n"
                                             "border-color: rgb(255, 255, 255);\n"
                                             "border-style: solid;")
        self.questionBtn1221_1.setText("")
        self.questionBtn1221_1.setIcon(icon1)
        self.questionBtn1221_1.setObjectName("questionBtn1221_1")
        self.horizontalLayout122_1.addWidget(self.questionBtn1221_1)
        self.verticalLayout_5.addLayout(self.horizontalLayout122_1)
        self.verticalLayout.addWidget(self.verticalGroupBox12_1)
        self.verticalGroupBox12_2 = QtWidgets.QGroupBox(self.verticalFrame1)
        self.verticalGroupBox12_2.setObjectName("verticalGroupBox12_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalGroupBox12_2)
        self.verticalLayout_6.setContentsMargins(10, 24, 10, 12)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout121_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout121_2.setObjectName("horizontalLayout121_2")
        self.label1_2 = QtWidgets.QLabel(self.verticalGroupBox12_2)
        self.label1_2.setObjectName("label1_2")
        self.horizontalLayout121_2.addWidget(self.label1_2)
        self.path1_2 = QtWidgets.QLineEdit(self.verticalGroupBox12_2)
        self.path1_2.setStyleSheet("border-width: 3px;\n"
                                   "border-radius: 5px;\n"
                                   "border-color: rgb(0, 0, 0);\n"
                                   "border-style: solid;\n"
                                   "background-color: rgb(188, 188, 188);\n"
                                   "color: rgb(0, 0, 0);")
        self.path1_2.setObjectName("path1_2")
        self.horizontalLayout121_2.addWidget(self.path1_2)
        self.uploadBtn1_2 = QtWidgets.QToolButton(self.verticalGroupBox12_2)
        self.uploadBtn1_2.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadBtn1_2.setMouseTracking(False)
        self.uploadBtn1_2.setAutoFillBackground(False)
        self.uploadBtn1_2.setStyleSheet("background-color: rgb(212, 212, 212);\n"
                                        "border-width: 3px;\n"
                                        "border-radius: 5px;\n"
                                        "border-color: rgb(0, 0, 0);\n"
                                        "border-style: solid;")
        self.uploadBtn1_2.setText("")
        self.uploadBtn1_2.setIcon(icon2)
        self.uploadBtn1_2.setObjectName("uploadBtn1_2")
        self.horizontalLayout121_2.addWidget(self.uploadBtn1_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout121_2)
        self.horizontalLayout122_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout122_2.setObjectName("horizontalLayout122_2")
        self.label2_2 = QtWidgets.QLabel(self.verticalGroupBox12_2)
        self.label2_2.setObjectName("label2_2")
        self.horizontalLayout122_2.addWidget(self.label2_2)
        self.path2_2 = QtWidgets.QLineEdit(self.verticalGroupBox12_2)
        self.path2_2.setStyleSheet("border-width: 3px;\n"
                                   "border-radius: 5px;\n"
                                   "border-color: rgb(0, 0, 0);\n"
                                   "border-style: solid;\n"
                                   "background-color: rgb(188, 188, 188);\n"
                                   "color: rgb(0, 0, 0);")
        self.path2_2.setObjectName("path2_2")
        self.horizontalLayout122_2.addWidget(self.path2_2)
        self.uploadBtn2_2 = QtWidgets.QToolButton(self.verticalGroupBox12_2)
        self.uploadBtn2_2.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadBtn2_2.setMouseTracking(False)
        self.uploadBtn2_2.setAutoFillBackground(False)
        self.uploadBtn2_2.setStyleSheet("background-color: rgb(212, 212, 212);\n"
                                        "border-width: 3px;\n"
                                        "border-radius: 5px;\n"
                                        "border-color: rgb(0, 0, 0);\n"
                                        "border-style: solid;")
        self.uploadBtn2_2.setText("")
        self.uploadBtn2_2.setIcon(icon2)
        self.uploadBtn2_2.setObjectName("uploadBtn2_2")
        self.horizontalLayout122_2.addWidget(self.uploadBtn2_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout122_2)
        self.horizontalLayout123_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout123_2.setObjectName("horizontalLayout123_2")
        self.label3_2 = QtWidgets.QLabel(self.verticalGroupBox12_2)
        self.label3_2.setObjectName("label3_2")
        self.horizontalLayout123_2.addWidget(self.label3_2)
        self.seperator = QtWidgets.QTextEdit(self.verticalGroupBox12_2)
        self.seperator.setStyleSheet("border-width: 3px;\n"
                                     "border-radius: 5px;\n"
                                     "border-color: rgb(0, 0, 0);\n"
                                     "border-style: solid;\n"
                                     "background-color: rgb(188, 188, 188);\n"
                                     "color: rgb(0, 0, 0);")
        self.seperator.setObjectName("seperator")
        self.horizontalLayout123_2.addWidget(self.seperator)
        self.questionBtn1231_2 = QtWidgets.QToolButton(self.verticalGroupBox12_2)
        self.questionBtn1231_2.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn1231_2.setMouseTracking(False)
        self.questionBtn1231_2.setAutoFillBackground(False)
        self.questionBtn1231_2.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                             "background-color: rgb(0, 0, 50);\n"
                                             "border-width: 1px;\n"
                                             "border-radius: 14px;\n"
                                             "border-color: rgb(255, 255, 255);\n"
                                             "border-style: solid;")
        self.questionBtn1231_2.setText("")
        self.questionBtn1231_2.setIcon(icon1)
        self.questionBtn1231_2.setObjectName("questionBtn1231_2")
        self.horizontalLayout123_2.addWidget(self.questionBtn1231_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout123_2)
        self.verticalLayout.addWidget(self.verticalGroupBox12_2)
        self.verticalGroupBox12_3 = QtWidgets.QGroupBox(self.verticalFrame1)
        self.verticalGroupBox12_3.setObjectName("verticalGroupBox12_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalGroupBox12_3)
        self.verticalLayout_7.setContentsMargins(10, 24, 10, 12)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout121_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout121_3.setContentsMargins(-1, 8, -1, 8)
        self.horizontalLayout121_3.setSpacing(10)
        self.horizontalLayout121_3.setObjectName("horizontalLayout121_3")
        self.label1_3 = QtWidgets.QLabel(self.verticalGroupBox12_3)
        self.label1_3.setObjectName("label1_3")
        self.horizontalLayout121_3.addWidget(self.label1_3)
        self.path1_3 = QtWidgets.QLineEdit(self.verticalGroupBox12_3)
        self.path1_3.setStyleSheet("border-width: 3px;\n"
                                   "border-radius: 5px;\n"
                                   "border-color: rgb(0, 0, 0);\n"
                                   "border-style: solid;\n"
                                   "background-color: rgb(188, 188, 188);\n"
                                   "color: rgb(0, 0, 0);")
        self.path1_3.setObjectName("path1_3")
        self.horizontalLayout121_3.addWidget(self.path1_3)
        self.uploadBtn1_3 = QtWidgets.QToolButton(self.verticalGroupBox12_3)
        self.uploadBtn1_3.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadBtn1_3.setMouseTracking(False)
        self.uploadBtn1_3.setAutoFillBackground(False)
        self.uploadBtn1_3.setStyleSheet("background-color: rgb(212, 212, 212);\n"
                                        "border-width: 3px;\n"
                                        "border-radius: 5px;\n"
                                        "border-color: rgb(0, 0, 0);\n"
                                        "border-style: solid;")
        self.uploadBtn1_3.setText("")
        self.uploadBtn1_3.setIcon(icon2)
        self.uploadBtn1_3.setObjectName("uploadBtn1_3")
        self.horizontalLayout121_3.addWidget(self.uploadBtn1_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout121_3)
        self.horizontalLayout122_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout122_3.setContentsMargins(-1, 8, -1, 8)
        self.horizontalLayout122_3.setSpacing(10)
        self.horizontalLayout122_3.setObjectName("horizontalLayout122_3")
        self.label2_3 = QtWidgets.QLabel(self.verticalGroupBox12_3)
        self.label2_3.setObjectName("label2_3")
        self.horizontalLayout122_3.addWidget(self.label2_3)
        self.path2_3 = QtWidgets.QLineEdit(self.verticalGroupBox12_3)
        self.path2_3.setStyleSheet("border-width: 3px;\n"
                                   "border-radius: 5px;\n"
                                   "border-color: rgb(0, 0, 0);\n"
                                   "border-style: solid;\n"
                                   "background-color: rgb(188, 188, 188);\n"
                                   "color: rgb(0, 0, 0);")
        self.path2_3.setObjectName("path2_3")
        self.horizontalLayout122_3.addWidget(self.path2_3)
        self.uploadBtn2_3 = QtWidgets.QToolButton(self.verticalGroupBox12_3)
        self.uploadBtn2_3.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadBtn2_3.setMouseTracking(False)
        self.uploadBtn2_3.setAutoFillBackground(False)
        self.uploadBtn2_3.setStyleSheet("background-color: rgb(212, 212, 212);\n"
                                        "border-width: 3px;\n"
                                        "border-radius: 5px;\n"
                                        "border-color: rgb(0, 0, 0);\n"
                                        "border-style: solid;")
        self.uploadBtn2_3.setText("")
        self.uploadBtn2_3.setIcon(icon2)
        self.uploadBtn2_3.setObjectName("uploadBtn2_3")
        self.horizontalLayout122_3.addWidget(self.uploadBtn2_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout122_3)
        self.verticalLayout.addWidget(self.verticalGroupBox12_3)
        self.errorMsg = QtWidgets.QLabel(self.groupBox)
        self.errorMsg.setGeometry(QtCore.QRect(20, 425, 81, 41))
        self.errorMsg.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.errorMsg.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0.983, y1:0.00568182, x2:0.996, y2:0, stop:1 rgba(48, 48, 48, 143));\n"
            "color: rgb(170, 0, 0);\n"
            "font: 75 8pt \"System\";\n"
            "border-radius: 10px;\n"
            "border-style: solid;\n"
            "border-width: 0px\n"
            "")
        self.errorMsg.setObjectName("errorMsg")
        self.verticalFrame2 = QtWidgets.QFrame(self.groupBox)
        self.verticalFrame2.setGeometry(QtCore.QRect(20, 100, 310, 320))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.verticalFrame2.setFont(font)
        self.verticalFrame2.setAutoFillBackground(False)
        self.verticalFrame2.setStyleSheet("border-width: 3px;\n"
                                          "border-radius: 15px;\n"
                                          "border-color: rgb(0, 0, 0);\n"
                                          "border-style: solid;\n"
                                          "font: 8pt \"Sitka Small\";\n"
                                          "color: rgb(255, 255, 255);\n"
                                          "background-color: qlineargradient(spread:pad, x1:0.996, y1:0.0340909, x2:1, y2:0, stop:1 rgba(0, 0, 32, 170));")
        self.verticalFrame2.setObjectName("verticalFrame2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame2)
        self.verticalLayout_3.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalGroupBox21 = QtWidgets.QGroupBox(self.verticalFrame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox21.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox21.setSizePolicy(sizePolicy)
        self.horizontalGroupBox21.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalGroupBox21.setStyleSheet("")
        self.horizontalGroupBox21.setObjectName("horizontalGroupBox21")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox21)
        self.horizontalLayout_3.setContentsMargins(10, 36, 10, 48)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.authorName = QtWidgets.QTextEdit(self.horizontalGroupBox21)
        self.authorName.setStyleSheet("border-width: 3px;\n"
                                      "border-radius: 5px;\n"
                                      "border-color: rgb(0, 0, 0);\n"
                                      "border-style: solid;\n"
                                      "background-color: rgb(188, 188, 188);\n"
                                      "color: rgb(0, 0, 0);")
        self.authorName.setObjectName("authorName")
        self.horizontalLayout_3.addWidget(self.authorName)
        self.questionBtn211 = QtWidgets.QToolButton(self.horizontalGroupBox21)
        self.questionBtn211.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn211.setMouseTracking(False)
        self.questionBtn211.setAutoFillBackground(False)
        self.questionBtn211.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                          "background-color: rgb(0, 0, 50);\n"
                                          "border-width: 1px;\n"
                                          "border-radius: 14px;\n"
                                          "border-color: rgb(255, 255, 255);\n"
                                          "border-style: solid;")
        self.questionBtn211.setText("")
        self.questionBtn211.setIcon(icon1)
        self.questionBtn211.setObjectName("questionBtn211")
        self.horizontalLayout_3.addWidget(self.questionBtn211)
        self.verticalLayout_3.addWidget(self.horizontalGroupBox21)
        self.verticalGroupBox22 = QtWidgets.QGroupBox(self.verticalFrame2)
        self.verticalGroupBox22.setObjectName("verticalGroupBox22")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalGroupBox22)
        self.verticalLayout_4.setContentsMargins(10, 24, 10, 12)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout221 = QtWidgets.QHBoxLayout()
        self.horizontalLayout221.setObjectName("horizontalLayout221")
        self.label2 = QtWidgets.QLabel(self.verticalGroupBox22)
        self.label2.setStyleSheet("font: 6pt \"Sitka Small\";")
        self.label2.setObjectName("label2")
        self.horizontalLayout221.addWidget(self.label2)
        self.trueLavel = QtWidgets.QTextEdit(self.verticalGroupBox22)
        self.trueLavel.setStyleSheet("border-width: 3px;\n"
                                     "border-radius: 5px;\n"
                                     "border-color: rgb(0, 0, 0);\n"
                                     "border-style: solid;\n"
                                     "background-color: rgb(188, 188, 188);\n"
                                     "color: rgb(0, 0, 0);")
        self.trueLavel.setObjectName("trueLavel")
        self.horizontalLayout221.addWidget(self.trueLavel)
        self.questionBtn2211 = QtWidgets.QToolButton(self.verticalGroupBox22)
        self.questionBtn2211.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn2211.setMouseTracking(False)
        self.questionBtn2211.setAutoFillBackground(False)
        self.questionBtn2211.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                           "background-color: rgb(0, 0, 50);\n"
                                           "border-width: 1px;\n"
                                           "border-radius: 14px;\n"
                                           "border-color: rgb(255, 255, 255);\n"
                                           "border-style: solid;")
        self.questionBtn2211.setText("")
        self.questionBtn2211.setIcon(icon1)
        self.questionBtn2211.setObjectName("questionBtn2211")
        self.horizontalLayout221.addWidget(self.questionBtn2211)
        self.verticalLayout_4.addLayout(self.horizontalLayout221)
        self.horizontalLayout222 = QtWidgets.QHBoxLayout()
        self.horizontalLayout222.setObjectName("horizontalLayout222")
        self.label3 = QtWidgets.QLabel(self.verticalGroupBox22)
        self.label3.setStyleSheet("font: 6pt \"Sitka Small\";")
        self.label3.setObjectName("label3")
        self.horizontalLayout222.addWidget(self.label3)
        self.fakeLabel = QtWidgets.QTextEdit(self.verticalGroupBox22)
        self.fakeLabel.setStyleSheet("border-width: 3px;\n"
                                     "border-radius: 5px;\n"
                                     "border-color: rgb(0, 0, 0);\n"
                                     "border-style: solid;\n"
                                     "background-color: rgb(188, 188, 188);\n"
                                     "color: rgb(0, 0, 0);")
        self.fakeLabel.setObjectName("fakeLabel")
        self.horizontalLayout222.addWidget(self.fakeLabel)
        self.questionBtn2221 = QtWidgets.QToolButton(self.verticalGroupBox22)
        self.questionBtn2221.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn2221.setMouseTracking(False)
        self.questionBtn2221.setAutoFillBackground(False)
        self.questionBtn2221.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                           "background-color: rgb(0, 0, 50);\n"
                                           "border-width: 1px;\n"
                                           "border-radius: 14px;\n"
                                           "border-color: rgb(255, 255, 255);\n"
                                           "border-style: solid;")
        self.questionBtn2221.setText("")
        self.questionBtn2221.setIcon(icon1)
        self.questionBtn2221.setObjectName("questionBtn2221")
        self.horizontalLayout222.addWidget(self.questionBtn2221)
        self.verticalLayout_4.addLayout(self.horizontalLayout222)
        self.verticalLayout_3.addWidget(self.verticalGroupBox22)
        TrainModelWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TrainModelWindow)
        QtCore.QMetaObject.connectSlotsByName(TrainModelWindow)

    def retranslateUi(self, TrainModelWindow):
        _translate = QtCore.QCoreApplication.translate
        TrainModelWindow.setWindowTitle(_translate("TrainModelWindow", "Train New Model"))
        self.groupBox.setTitle(_translate("TrainModelWindow", "Train a new Model"))
        self.trainBtn.setText(_translate("TrainModelWindow", "Train"))
        self.backBtn.setText(_translate("TrainModelWindow", "Back"))
        self.verticalGroupBox11.setTitle(_translate("TrainModelWindow", "Choose a relevant format of your DB:"))
        self.radioButton1112.setText(_translate("TrainModelWindow", "CSV File with column for label"))
        self.radioButton1122.setText(_translate("TrainModelWindow", "Two seperated files for each label"))
        self.radioButton1132.setText(_translate("TrainModelWindow", "Two seperated folders for each label"))
        self.verticalGroupBox12_1.setTitle(_translate("TrainModelWindow", "Upload CSV file:"))
        self.label1_1.setText(_translate("TrainModelWindow", "Column name:"))
        self.verticalGroupBox12_2.setTitle(_translate("TrainModelWindow", "Upload two files:"))
        self.label1_2.setText(_translate("TrainModelWindow", "File1:"))
        self.label2_2.setText(_translate("TrainModelWindow", "File1:"))
        self.label3_2.setText(_translate("TrainModelWindow", "seperator:"))
        self.verticalGroupBox12_3.setTitle(_translate("TrainModelWindow", "Upload two folders:"))
        self.label1_3.setText(_translate("TrainModelWindow", "Folder 1:"))
        self.label2_3.setText(_translate("TrainModelWindow", "Folder 2:"))
        self.errorMsg.setText(_translate("TrainModelWindow", "warning"))
        self.horizontalGroupBox21.setTitle(_translate("TrainModelWindow", "Author name:"))
        self.verticalGroupBox22.setTitle(_translate("TrainModelWindow", "Labels names:"))
        self.label2.setText(_translate("TrainModelWindow", "Label 1 (+):"))
        self.label3.setText(_translate("TrainModelWindow", "Label 2 (-):"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    TrainModelWindow = QtWidgets.QMainWindow()
    ui = Ui_TrainModelWindow()
    ui.setupUi(TrainModelWindow)
    TrainModelWindow.show()
    sys.exit(app.exec_())
