# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'train_model_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrainModelWindow(object):
    def setupUi(self, TrainModelWindow):
        TrainModelWindow.setObjectName("TrainModelWindow")
        TrainModelWindow.resize(860, 598)
        self.centralwidget = QtWidgets.QWidget(TrainModelWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundImg = QtWidgets.QLabel(self.centralwidget)
        self.backgroundImg.setGeometry(QtCore.QRect(0, 0, 860, 600))
        self.backgroundImg.setText("")
        self.backgroundImg.setPixmap(QtGui.QPixmap("resources/background.jpg"))
        self.backgroundImg.setScaledContents(True)
        self.backgroundImg.setObjectName("backgroundImg")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(30, 0, 800, 570))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);\n"
                                    "                    ")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.trainBtn = QtWidgets.QPushButton(self.groupBox)
        self.trainBtn.setEnabled(True)
        self.trainBtn.setGeometry(QtCore.QRect(530, 479, 240, 60))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.trainBtn.setFont(font)
        self.trainBtn.setAcceptDrops(False)
        self.trainBtn.setAutoFillBackground(False)
        self.trainBtn.setStyleSheet("\n"
                                    "                            background-color: rgb(0, 0, 20);\n"
                                    "                            font: 75 16pt \"Sitka Small\";\n"
                                    "                            color: rgb(255, 255, 255);\n"
                                    "                            border-width: 3px;\n"
                                    "                            border-radius: 30px;\n"
                                    "                            border-color: rgb(255, 255, 255);\n"
                                    "                            border-style: solid;\n"
                                    "                        ")
        self.trainBtn.setCheckable(False)
        self.trainBtn.setAutoDefault(False)
        self.trainBtn.setDefault(False)
        self.trainBtn.setFlat(False)
        self.trainBtn.setObjectName("trainBtn")
        self.backBtn = QtWidgets.QPushButton(self.groupBox)
        self.backBtn.setEnabled(True)
        self.backBtn.setGeometry(QtCore.QRect(30, 479, 240, 60))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.backBtn.setFont(font)
        self.backBtn.setAcceptDrops(False)
        self.backBtn.setAutoFillBackground(False)
        self.backBtn.setStyleSheet("\n"
                                   "                            background-color: rgb(159, 0, 0);\n"
                                   "                            font: 75 16pt \"Sitka Small\";\n"
                                   "                            color: rgb(255, 255, 255);\n"
                                   "                            border-width: 3px;\n"
                                   "                            border-radius: 30px;\n"
                                   "                            border-color: rgb(255, 255, 255);\n"
                                   "                            border-style: solid;\n"
                                   "                        ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/My Documents/Studies/Semester_9/פרויקט מסכם - שלב\n"
                                     "                                ב/icons/pnghut_arrow-icon-direction-left-logo-text.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backBtn.setIcon(icon)
        self.backBtn.setIconSize(QtCore.QSize(24, 24))
        self.backBtn.setCheckable(False)
        self.backBtn.setAutoDefault(False)
        self.backBtn.setDefault(False)
        self.backBtn.setFlat(False)
        self.backBtn.setObjectName("backBtn")
        self.verticalFrame1 = QtWidgets.QFrame(self.groupBox)
        self.verticalFrame1.setGeometry(QtCore.QRect(340, 100, 440, 370))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.verticalFrame1.setFont(font)
        self.verticalFrame1.setAutoFillBackground(False)
        self.verticalFrame1.setStyleSheet("border-width: 3px;\n"
                                          "                            border-radius: 15px;\n"
                                          "                            border-color: rgb(0, 0, 0);\n"
                                          "                            border-style: solid;\n"
                                          "                            font: 8pt \"Sitka Small\";\n"
                                          "                            color: rgb(255, 255, 255);\n"
                                          "                            background-color: qlineargradient(spread:pad, x1:0.996, y1:0.0340909, x2:1, y2:0, stop:1\n"
                                          "                            rgba(0, 0, 32, 170));\n"
                                          "                        ")
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalGroupBox11 = QtWidgets.QGroupBox(self.verticalFrame1)
        self.verticalGroupBox11.setObjectName("verticalGroupBox11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox11)
        self.verticalLayout_2.setContentsMargins(10, 24, 10, 12)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout111 = QtWidgets.QHBoxLayout()
        self.horizontalLayout111.setObjectName("horizontalLayout111")
        self.radioButton1112 = QtWidgets.QRadioButton(self.verticalGroupBox11)
        self.radioButton1112.setAutoFillBackground(False)
        self.radioButton1112.setChecked(True)
        self.radioButton1112.setObjectName("radioButton1112")
        self.horizontalLayout111.addWidget(self.radioButton1112)
        self.questionBtn1111 = QtWidgets.QToolButton(self.verticalGroupBox11)
        self.questionBtn1111.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn1111.setMouseTracking(False)
        self.questionBtn1111.setAutoFillBackground(False)
        self.questionBtn1111.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                           "                                                            background-color: rgb(0, 0, 50);\n"
                                           "                                                            border-width: 1px;\n"
                                           "                                                            border-radius: 14px;\n"
                                           "                                                            border-color: rgb(255, 255, 255);\n"
                                           "                                                            border-style: solid;\n"
                                           "                                                        ")
        self.questionBtn1111.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/question_icon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.questionBtn1111.setIcon(icon1)
        self.questionBtn1111.setObjectName("questionBtn1111")
        self.horizontalLayout111.addWidget(self.questionBtn1111)
        self.verticalLayout_2.addLayout(self.horizontalLayout111)
        self.horizontalLayout112 = QtWidgets.QHBoxLayout()
        self.horizontalLayout112.setObjectName("horizontalLayout112")
        self.radioButton1122 = QtWidgets.QRadioButton(self.verticalGroupBox11)
        self.radioButton1122.setObjectName("radioButton1122")
        self.horizontalLayout112.addWidget(self.radioButton1122)
        self.questionBtn1121 = QtWidgets.QToolButton(self.verticalGroupBox11)
        self.questionBtn1121.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn1121.setMouseTracking(False)
        self.questionBtn1121.setAutoFillBackground(False)
        self.questionBtn1121.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                           "                                                            background-color: rgb(0, 0, 50);\n"
                                           "                                                            border-width: 1px;\n"
                                           "                                                            border-radius: 14px;\n"
                                           "                                                            border-color: rgb(255, 255, 255);\n"
                                           "                                                            border-style: solid;\n"
                                           "                                                        ")
        self.questionBtn1121.setText("")
        self.questionBtn1121.setIcon(icon1)
        self.questionBtn1121.setObjectName("questionBtn1121")
        self.horizontalLayout112.addWidget(self.questionBtn1121)
        self.verticalLayout_2.addLayout(self.horizontalLayout112)
        self.horizontalLayout113 = QtWidgets.QHBoxLayout()
        self.horizontalLayout113.setObjectName("horizontalLayout113")
        self.radioButton1132 = QtWidgets.QRadioButton(self.verticalGroupBox11)
        self.radioButton1132.setObjectName("radioButton1132")
        self.horizontalLayout113.addWidget(self.radioButton1132)
        self.questionBtn1131 = QtWidgets.QToolButton(self.verticalGroupBox11)
        self.questionBtn1131.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn1131.setMouseTracking(False)
        self.questionBtn1131.setAutoFillBackground(False)
        self.questionBtn1131.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                           "                                                            background-color: rgb(0, 0, 50);\n"
                                           "                                                            border-width: 1px;\n"
                                           "                                                            border-radius: 14px;\n"
                                           "                                                            border-color: rgb(255, 255, 255);\n"
                                           "                                                            border-style: solid;\n"
                                           "                                                        ")
        self.questionBtn1131.setText("")
        self.questionBtn1131.setIcon(icon1)
        self.questionBtn1131.setObjectName("questionBtn1131")
        self.horizontalLayout113.addWidget(self.questionBtn1131)
        self.verticalLayout_2.addLayout(self.horizontalLayout113)
        self.verticalLayout.addWidget(self.verticalGroupBox11)
        self.verticalGroupBox12 = QtWidgets.QGroupBox(self.verticalFrame1)
        self.verticalGroupBox12.setObjectName("verticalGroupBox12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalGroupBox12)
        self.verticalLayout_5.setContentsMargins(10, 24, 10, 12)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout121 = QtWidgets.QHBoxLayout()
        self.horizontalLayout121.setObjectName("horizontalLayout121")
        self.path1211 = QtWidgets.QLineEdit(self.verticalGroupBox12)
        self.path1211.setStyleSheet("border-width: 3px;\n"
                                    "                                                            border-radius: 5px;\n"
                                    "                                                            border-color: rgb(0, 0, 0);\n"
                                    "                                                            border-style: solid;\n"
                                    "                                                            background-color: rgb(188, 188, 188);\n"
                                    "                                                            color: rgb(0, 0, 0);\n"
                                    "                                                        ")
        self.path1211.setObjectName("path1211")
        self.horizontalLayout121.addWidget(self.path1211)
        self.uploadBtn1212 = QtWidgets.QToolButton(self.verticalGroupBox12)
        self.uploadBtn1212.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadBtn1212.setMouseTracking(False)
        self.uploadBtn1212.setAutoFillBackground(False)
        self.uploadBtn1212.setStyleSheet("background-color: rgb(212, 212, 212);\n"
                                         "                                                            border-width: 3px;\n"
                                         "                                                            border-radius: 5px;\n"
                                         "                                                            border-color: rgb(0, 0, 0);\n"
                                         "                                                            border-style: solid;\n"
                                         "                                                        ")
        self.uploadBtn1212.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/upload_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uploadBtn1212.setIcon(icon2)
        self.uploadBtn1212.setObjectName("uploadBtn1212")
        self.horizontalLayout121.addWidget(self.uploadBtn1212)
        self.verticalLayout_5.addLayout(self.horizontalLayout121)
        self.horizontalLayout122 = QtWidgets.QHBoxLayout()
        self.horizontalLayout122.setContentsMargins(-1, 16, -1, 16)
        self.horizontalLayout122.setObjectName("horizontalLayout122")
        self.label1222 = QtWidgets.QLabel(self.verticalGroupBox12)
        self.label1222.setObjectName("label1222")
        self.horizontalLayout122.addWidget(self.label1222)
        self.columnName1221 = QtWidgets.QTextEdit(self.verticalGroupBox12)
        self.columnName1221.setStyleSheet("border-width: 3px;\n"
                                          "                                                            border-radius: 5px;\n"
                                          "                                                            border-color: rgb(0, 0, 0);\n"
                                          "                                                            border-style: solid;\n"
                                          "                                                            background-color: rgb(188, 188, 188);\n"
                                          "                                                            color: rgb(0, 0, 0);\n"
                                          "                                                        ")
        self.columnName1221.setObjectName("columnName1221")
        self.horizontalLayout122.addWidget(self.columnName1221)
        self.questionBtn1223 = QtWidgets.QToolButton(self.verticalGroupBox12)
        self.questionBtn1223.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn1223.setMouseTracking(False)
        self.questionBtn1223.setAutoFillBackground(False)
        self.questionBtn1223.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                           "                                                            background-color: rgb(0, 0, 50);\n"
                                           "                                                            border-width: 1px;\n"
                                           "                                                            border-radius: 14px;\n"
                                           "                                                            border-color: rgb(255, 255, 255);\n"
                                           "                                                            border-style: solid;\n"
                                           "                                                        ")
        self.questionBtn1223.setText("")
        self.questionBtn1223.setIcon(icon1)
        self.questionBtn1223.setObjectName("questionBtn1223")
        self.horizontalLayout122.addWidget(self.questionBtn1223)
        self.verticalLayout_5.addLayout(self.horizontalLayout122)
        self.verticalLayout.addWidget(self.verticalGroupBox12)
        self.verticalGroupBox13 = QtWidgets.QGroupBox(self.verticalFrame1)
        self.verticalGroupBox13.setObjectName("verticalGroupBox13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalGroupBox13)
        self.verticalLayout_6.setContentsMargins(10, 24, 10, 12)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout131 = QtWidgets.QHBoxLayout()
        self.horizontalLayout131.setObjectName("horizontalLayout131")
        self.label1311 = QtWidgets.QLabel(self.verticalGroupBox13)
        self.label1311.setObjectName("label1311")
        self.horizontalLayout131.addWidget(self.label1311)
        self.path1312 = QtWidgets.QLineEdit(self.verticalGroupBox13)
        self.path1312.setStyleSheet("border-width: 3px;\n"
                                    "                                                            border-radius: 5px;\n"
                                    "                                                            border-color: rgb(0, 0, 0);\n"
                                    "                                                            border-style: solid;\n"
                                    "                                                            background-color: rgb(188, 188, 188);\n"
                                    "                                                            color: rgb(0, 0, 0);\n"
                                    "                                                        ")
        self.path1312.setObjectName("path1312")
        self.horizontalLayout131.addWidget(self.path1312)
        self.uploadBtn1313 = QtWidgets.QToolButton(self.verticalGroupBox13)
        self.uploadBtn1313.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadBtn1313.setMouseTracking(False)
        self.uploadBtn1313.setAutoFillBackground(False)
        self.uploadBtn1313.setStyleSheet("background-color: rgb(212, 212, 212);\n"
                                         "                                                            border-width: 3px;\n"
                                         "                                                            border-radius: 5px;\n"
                                         "                                                            border-color: rgb(0, 0, 0);\n"
                                         "                                                            border-style: solid;\n"
                                         "                                                        ")
        self.uploadBtn1313.setText("")
        self.uploadBtn1313.setIcon(icon2)
        self.uploadBtn1313.setObjectName("uploadBtn1313")
        self.horizontalLayout131.addWidget(self.uploadBtn1313)
        self.verticalLayout_6.addLayout(self.horizontalLayout131)
        self.horizontalLayout132 = QtWidgets.QHBoxLayout()
        self.horizontalLayout132.setObjectName("horizontalLayout132")
        self.label1321 = QtWidgets.QLabel(self.verticalGroupBox13)
        self.label1321.setObjectName("label1321")
        self.horizontalLayout132.addWidget(self.label1321)
        self.path1322 = QtWidgets.QLineEdit(self.verticalGroupBox13)
        self.path1322.setStyleSheet("border-width: 3px;\n"
                                    "                                                            border-radius: 5px;\n"
                                    "                                                            border-color: rgb(0, 0, 0);\n"
                                    "                                                            border-style: solid;\n"
                                    "                                                            background-color: rgb(188, 188, 188);\n"
                                    "                                                            color: rgb(0, 0, 0);\n"
                                    "                                                        ")
        self.path1322.setObjectName("path1322")
        self.horizontalLayout132.addWidget(self.path1322)
        self.uploadBtn1323 = QtWidgets.QToolButton(self.verticalGroupBox13)
        self.uploadBtn1323.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadBtn1323.setMouseTracking(False)
        self.uploadBtn1323.setAutoFillBackground(False)
        self.uploadBtn1323.setStyleSheet("background-color: rgb(212, 212, 212);\n"
                                         "                                                            border-width: 3px;\n"
                                         "                                                            border-radius: 5px;\n"
                                         "                                                            border-color: rgb(0, 0, 0);\n"
                                         "                                                            border-style: solid;\n"
                                         "                                                        ")
        self.uploadBtn1323.setText("")
        self.uploadBtn1323.setIcon(icon2)
        self.uploadBtn1323.setObjectName("uploadBtn1323")
        self.horizontalLayout132.addWidget(self.uploadBtn1323)
        self.verticalLayout_6.addLayout(self.horizontalLayout132)
        self.horizontalLayout133 = QtWidgets.QHBoxLayout()
        self.horizontalLayout133.setObjectName("horizontalLayout133")
        self.label1331 = QtWidgets.QLabel(self.verticalGroupBox13)
        self.label1331.setObjectName("label1331")
        self.horizontalLayout133.addWidget(self.label1331)
        self.seperator1333 = QtWidgets.QTextEdit(self.verticalGroupBox13)
        self.seperator1333.setStyleSheet("border-width: 3px;\n"
                                         "                                                            border-radius: 5px;\n"
                                         "                                                            border-color: rgb(0, 0, 0);\n"
                                         "                                                            border-style: solid;\n"
                                         "                                                            background-color: rgb(188, 188, 188);\n"
                                         "                                                            color: rgb(0, 0, 0);\n"
                                         "                                                        ")
        self.seperator1333.setObjectName("seperator1333")
        self.horizontalLayout133.addWidget(self.seperator1333)
        self.questionBtn1332 = QtWidgets.QToolButton(self.verticalGroupBox13)
        self.questionBtn1332.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn1332.setMouseTracking(False)
        self.questionBtn1332.setAutoFillBackground(False)
        self.questionBtn1332.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                           "                                                            background-color: rgb(0, 0, 50);\n"
                                           "                                                            border-width: 1px;\n"
                                           "                                                            border-radius: 14px;\n"
                                           "                                                            border-color: rgb(255, 255, 255);\n"
                                           "                                                            border-style: solid;\n"
                                           "                                                        ")
        self.questionBtn1332.setText("")
        self.questionBtn1332.setIcon(icon1)
        self.questionBtn1332.setObjectName("questionBtn1332")
        self.horizontalLayout133.addWidget(self.questionBtn1332)
        self.verticalLayout_6.addLayout(self.horizontalLayout133)
        self.verticalLayout.addWidget(self.verticalGroupBox13)
        self.verticalGroupBox14 = QtWidgets.QGroupBox(self.verticalFrame1)
        self.verticalGroupBox14.setObjectName("verticalGroupBox14")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalGroupBox14)
        self.verticalLayout_7.setContentsMargins(10, 24, 10, 12)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout141 = QtWidgets.QHBoxLayout()
        self.horizontalLayout141.setContentsMargins(-1, 8, -1, 8)
        self.horizontalLayout141.setSpacing(10)
        self.horizontalLayout141.setObjectName("horizontalLayout141")
        self.label1411 = QtWidgets.QLabel(self.verticalGroupBox14)
        self.label1411.setObjectName("label1411")
        self.horizontalLayout141.addWidget(self.label1411)
        self.path1412 = QtWidgets.QLineEdit(self.verticalGroupBox14)
        self.path1412.setStyleSheet("border-width: 3px;\n"
                                    "                                                            border-radius: 5px;\n"
                                    "                                                            border-color: rgb(0, 0, 0);\n"
                                    "                                                            border-style: solid;\n"
                                    "                                                            background-color: rgb(188, 188, 188);\n"
                                    "                                                            color: rgb(0, 0, 0);\n"
                                    "                                                        ")
        self.path1412.setObjectName("path1412")
        self.horizontalLayout141.addWidget(self.path1412)
        self.uploadBtn1413 = QtWidgets.QToolButton(self.verticalGroupBox14)
        self.uploadBtn1413.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadBtn1413.setMouseTracking(False)
        self.uploadBtn1413.setAutoFillBackground(False)
        self.uploadBtn1413.setStyleSheet("background-color: rgb(212, 212, 212);\n"
                                         "                                                            border-width: 3px;\n"
                                         "                                                            border-radius: 5px;\n"
                                         "                                                            border-color: rgb(0, 0, 0);\n"
                                         "                                                            border-style: solid;\n"
                                         "                                                        ")
        self.uploadBtn1413.setText("")
        self.uploadBtn1413.setIcon(icon2)
        self.uploadBtn1413.setObjectName("uploadBtn1413")
        self.horizontalLayout141.addWidget(self.uploadBtn1413)
        self.verticalLayout_7.addLayout(self.horizontalLayout141)
        self.horizontalLayout142 = QtWidgets.QHBoxLayout()
        self.horizontalLayout142.setContentsMargins(-1, 8, -1, 8)
        self.horizontalLayout142.setSpacing(10)
        self.horizontalLayout142.setObjectName("horizontalLayout142")
        self.label1421 = QtWidgets.QLabel(self.verticalGroupBox14)
        self.label1421.setObjectName("label1421")
        self.horizontalLayout142.addWidget(self.label1421)
        self.path1422 = QtWidgets.QLineEdit(self.verticalGroupBox14)
        self.path1422.setStyleSheet("border-width: 3px;\n"
                                    "                                                            border-radius: 5px;\n"
                                    "                                                            border-color: rgb(0, 0, 0);\n"
                                    "                                                            border-style: solid;\n"
                                    "                                                            background-color: rgb(188, 188, 188);\n"
                                    "                                                            color: rgb(0, 0, 0);\n"
                                    "                                                        ")
        self.path1422.setObjectName("path1422")
        self.horizontalLayout142.addWidget(self.path1422)
        self.uploadBtn1423 = QtWidgets.QToolButton(self.verticalGroupBox14)
        self.uploadBtn1423.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadBtn1423.setMouseTracking(False)
        self.uploadBtn1423.setAutoFillBackground(False)
        self.uploadBtn1423.setStyleSheet("background-color: rgb(212, 212, 212);\n"
                                         "                                                            border-width: 3px;\n"
                                         "                                                            border-radius: 5px;\n"
                                         "                                                            border-color: rgb(0, 0, 0);\n"
                                         "                                                            border-style: solid;\n"
                                         "                                                        ")
        self.uploadBtn1423.setText("")
        self.uploadBtn1423.setIcon(icon2)
        self.uploadBtn1423.setObjectName("uploadBtn1423")
        self.horizontalLayout142.addWidget(self.uploadBtn1423)
        self.verticalLayout_7.addLayout(self.horizontalLayout142)
        self.verticalLayout.addWidget(self.verticalGroupBox14)
        self.errorMsg = QtWidgets.QLabel(self.groupBox)
        self.errorMsg.setGeometry(QtCore.QRect(20, 425, 81, 41))
        self.errorMsg.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.errorMsg.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.983, y1:0.00568182,\n"
                                    "                            x2:0.996, y2:0, stop:1 rgba(48, 48, 48, 143));\n"
                                    "                            color: rgb(170, 0, 0);\n"
                                    "                            font: 75 8pt \"System\";\n"
                                    "                            border-radius: 10px;\n"
                                    "                            border-style: solid;\n"
                                    "                            border-width: 0px\n"
                                    "                        ")
        self.errorMsg.setObjectName("errorMsg")
        self.verticalFrame2 = QtWidgets.QFrame(self.groupBox)
        self.verticalFrame2.setGeometry(QtCore.QRect(20, 100, 310, 320))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.verticalFrame2.setFont(font)
        self.verticalFrame2.setAutoFillBackground(False)
        self.verticalFrame2.setStyleSheet("border-width: 3px;\n"
                                          "                            border-radius: 15px;\n"
                                          "                            border-color: rgb(0, 0, 0);\n"
                                          "                            border-style: solid;\n"
                                          "                            font: 8pt \"Sitka Small\";\n"
                                          "                            color: rgb(255, 255, 255);\n"
                                          "                            background-color: qlineargradient(spread:pad, x1:0.996, y1:0.0340909, x2:1, y2:0, stop:1\n"
                                          "                            rgba(0, 0, 32, 170));\n"
                                          "                        ")
        self.verticalFrame2.setObjectName("verticalFrame2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame2)
        self.verticalLayout_3.setContentsMargins(18, 18, 18, 18)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalGroupBox21 = QtWidgets.QGroupBox(self.verticalFrame2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox21.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox21.setSizePolicy(sizePolicy)
        self.horizontalGroupBox21.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalGroupBox21.setStyleSheet("")
        self.horizontalGroupBox21.setObjectName("horizontalGroupBox21")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox21)
        self.horizontalLayout_3.setContentsMargins(10, 36, 10, 48)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.authorName211 = QtWidgets.QTextEdit(self.horizontalGroupBox21)
        self.authorName211.setStyleSheet("border-width: 3px;\n"
                                         "                                                    border-radius: 5px;\n"
                                         "                                                    border-color: rgb(0, 0, 0);\n"
                                         "                                                    border-style: solid;\n"
                                         "                                                    background-color: rgb(188, 188, 188);\n"
                                         "                                                    color: rgb(0, 0, 0);\n"
                                         "                                                ")
        self.authorName211.setObjectName("authorName211")
        self.horizontalLayout_3.addWidget(self.authorName211)
        self.questionBtn212 = QtWidgets.QToolButton(self.horizontalGroupBox21)
        self.questionBtn212.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn212.setMouseTracking(False)
        self.questionBtn212.setAutoFillBackground(False)
        self.questionBtn212.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                          "                                                    background-color: rgb(0, 0, 50);\n"
                                          "                                                    border-width: 1px;\n"
                                          "                                                    border-radius: 14px;\n"
                                          "                                                    border-color: rgb(255, 255, 255);\n"
                                          "                                                    border-style: solid;\n"
                                          "                                                ")
        self.questionBtn212.setText("")
        self.questionBtn212.setIcon(icon1)
        self.questionBtn212.setObjectName("questionBtn212")
        self.horizontalLayout_3.addWidget(self.questionBtn212)
        self.verticalLayout_3.addWidget(self.horizontalGroupBox21)
        self.verticalGroupBox22 = QtWidgets.QGroupBox(self.verticalFrame2)
        self.verticalGroupBox22.setObjectName("verticalGroupBox22")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalGroupBox22)
        self.verticalLayout_4.setContentsMargins(10, 24, 10, 12)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout221 = QtWidgets.QHBoxLayout()
        self.horizontalLayout221.setObjectName("horizontalLayout221")
        self.label2211 = QtWidgets.QLabel(self.verticalGroupBox22)
        self.label2211.setStyleSheet("font: 6pt \"Sitka Small\";")
        self.label2211.setObjectName("label2211")
        self.horizontalLayout221.addWidget(self.label2211)
        self.trueLavel2213 = QtWidgets.QTextEdit(self.verticalGroupBox22)
        self.trueLavel2213.setStyleSheet("border-width: 3px;\n"
                                         "                                                            border-radius: 5px;\n"
                                         "                                                            border-color: rgb(0, 0, 0);\n"
                                         "                                                            border-style: solid;\n"
                                         "                                                            background-color: rgb(188, 188, 188);\n"
                                         "                                                            color: rgb(0, 0, 0);\n"
                                         "                                                        ")
        self.trueLavel2213.setObjectName("trueLavel2213")
        self.horizontalLayout221.addWidget(self.trueLavel2213)
        self.questionBtn2212 = QtWidgets.QToolButton(self.verticalGroupBox22)
        self.questionBtn2212.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn2212.setMouseTracking(False)
        self.questionBtn2212.setAutoFillBackground(False)
        self.questionBtn2212.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                           "                                                            background-color: rgb(0, 0, 50);\n"
                                           "                                                            border-width: 1px;\n"
                                           "                                                            border-radius: 14px;\n"
                                           "                                                            border-color: rgb(255, 255, 255);\n"
                                           "                                                            border-style: solid;\n"
                                           "                                                        ")
        self.questionBtn2212.setText("")
        self.questionBtn2212.setIcon(icon1)
        self.questionBtn2212.setObjectName("questionBtn2212")
        self.horizontalLayout221.addWidget(self.questionBtn2212)
        self.verticalLayout_4.addLayout(self.horizontalLayout221)
        self.horizontalLayout222 = QtWidgets.QHBoxLayout()
        self.horizontalLayout222.setObjectName("horizontalLayout222")
        self.label2222 = QtWidgets.QLabel(self.verticalGroupBox22)
        self.label2222.setStyleSheet("font: 6pt \"Sitka Small\";")
        self.label2222.setObjectName("label2222")
        self.horizontalLayout222.addWidget(self.label2222)
        self.fakeLabel2221 = QtWidgets.QTextEdit(self.verticalGroupBox22)
        self.fakeLabel2221.setStyleSheet("border-width: 3px;\n"
                                         "                                                            border-radius: 5px;\n"
                                         "                                                            border-color: rgb(0, 0, 0);\n"
                                         "                                                            border-style: solid;\n"
                                         "                                                            background-color: rgb(188, 188, 188);\n"
                                         "                                                            color: rgb(0, 0, 0);\n"
                                         "                                                        ")
        self.fakeLabel2221.setObjectName("fakeLabel2221")
        self.horizontalLayout222.addWidget(self.fakeLabel2221)
        self.questionBtn2223 = QtWidgets.QToolButton(self.verticalGroupBox22)
        self.questionBtn2223.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn2223.setMouseTracking(False)
        self.questionBtn2223.setAutoFillBackground(False)
        self.questionBtn2223.setStyleSheet("background-color: rgb(0, 0, 127);\n"
                                           "                                                            background-color: rgb(0, 0, 50);\n"
                                           "                                                            border-width: 1px;\n"
                                           "                                                            border-radius: 14px;\n"
                                           "                                                            border-color: rgb(255, 255, 255);\n"
                                           "                                                            border-style: solid;\n"
                                           "                                                        ")
        self.questionBtn2223.setText("")
        self.questionBtn2223.setIcon(icon1)
        self.questionBtn2223.setObjectName("questionBtn2223")
        self.horizontalLayout222.addWidget(self.questionBtn2223)
        self.verticalLayout_4.addLayout(self.horizontalLayout222)
        self.verticalLayout_3.addWidget(self.verticalGroupBox22)
        TrainModelWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TrainModelWindow)
        QtCore.QMetaObject.connectSlotsByName(TrainModelWindow)

    def retranslateUi(self, TrainModelWindow):
        _translate = QtCore.QCoreApplication.translate
        TrainModelWindow.setWindowTitle(_translate("TrainModelWindow", "Train New Model"))
        self.groupBox.setTitle(_translate("TrainModelWindow", "Train a new Model"))
        self.trainBtn.setText(_translate("TrainModelWindow", "Train"))
        self.backBtn.setText(_translate("TrainModelWindow", "Back"))
        self.verticalGroupBox11.setTitle(_translate("TrainModelWindow", "Choose a relevant format of your database:"))
        self.radioButton1112.setText(_translate("TrainModelWindow", "CSV File with column for label"))
        self.radioButton1122.setText(_translate("TrainModelWindow", "Two seperated files for each label"))
        self.radioButton1132.setText(_translate("TrainModelWindow", "Two seperated folders for each label"))
        self.verticalGroupBox12.setTitle(_translate("TrainModelWindow", "Upload CSV file:"))
        self.label1222.setText(_translate("TrainModelWindow", "Column name:"))
        self.verticalGroupBox13.setTitle(_translate("TrainModelWindow", "Upload two files:"))
        self.label1311.setText(_translate("TrainModelWindow", "File1:"))
        self.label1321.setText(_translate("TrainModelWindow", "File1:"))
        self.label1331.setText(_translate("TrainModelWindow", "seperator:"))
        self.verticalGroupBox14.setTitle(_translate("TrainModelWindow", "Upload two folders:"))
        self.label1411.setText(_translate("TrainModelWindow", "Folder 1:"))
        self.label1421.setText(_translate("TrainModelWindow", "Folder 2:"))
        self.errorMsg.setText(_translate("TrainModelWindow", "warning"))
        self.horizontalGroupBox21.setTitle(_translate("TrainModelWindow", "Author name:"))
        self.verticalGroupBox22.setTitle(_translate("TrainModelWindow", "Labels names:"))
        self.label2211.setText(_translate("TrainModelWindow", "Label 1 (+):"))
        self.label2222.setText(_translate("TrainModelWindow", "Label 2 (-):"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    TrainModelWindow = QtWidgets.QMainWindow()
    ui = Ui_TrainModelWindow()
    ui.setupUi(TrainModelWindow)
    TrainModelWindow.show()
    sys.exit(app.exec_())
