# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundImg = QtWidgets.QLabel(self.centralwidget)
        self.backgroundImg.setGeometry(QtCore.QRect(0, 0, 860, 600))
        self.backgroundImg.setText("")
        self.backgroundImg.setPixmap(QtGui.QPixmap("../RESOURCES/background2.jpg"))
        self.backgroundImg.setScaledContents(True)
        self.backgroundImg.setObjectName("backgroundImg")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(30, 0, 800, 570))
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"border-width: 1px;\n"
"border-width: 1px;\n"
"")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.plagiarismBtn = QtWidgets.QPushButton(self.groupBox)
        self.plagiarismBtn.setEnabled(True)
        self.plagiarismBtn.setGeometry(QtCore.QRect(90, 190, 260, 111))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.plagiarismBtn.setFont(font)
        self.plagiarismBtn.setAcceptDrops(False)
        self.plagiarismBtn.setAutoFillBackground(False)
        self.plagiarismBtn.setStyleSheet("\n"
"background-color: rgb(133, 138, 144);\n"
"font: 75 18pt \"Sitka Small\";\n"
"color: rgb(0, 0, 0);\n"
"border-width: 3px;\n"
"background-color: rgb(93, 255, 85);\n"
"border-radius: 30px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style: solid;")
        self.plagiarismBtn.setCheckable(False)
        self.plagiarismBtn.setAutoDefault(False)
        self.plagiarismBtn.setDefault(False)
        self.plagiarismBtn.setFlat(False)
        self.plagiarismBtn.setObjectName("plagiarismBtn")
        self.fakeNewsBtn = QtWidgets.QPushButton(self.groupBox)
        self.fakeNewsBtn.setEnabled(True)
        self.fakeNewsBtn.setGeometry(QtCore.QRect(450, 190, 260, 110))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.fakeNewsBtn.setFont(font)
        self.fakeNewsBtn.setAcceptDrops(False)
        self.fakeNewsBtn.setAutoFillBackground(False)
        self.fakeNewsBtn.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"font: 75 18pt \"Sitka Small\";\n"
"color: rgb(0, 0, 0);\n"
"border-width: 3px;\n"
"border-radius: 30px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style: solid;")
        self.fakeNewsBtn.setCheckable(False)
        self.fakeNewsBtn.setAutoDefault(False)
        self.fakeNewsBtn.setDefault(False)
        self.fakeNewsBtn.setFlat(False)
        self.fakeNewsBtn.setObjectName("fakeNewsBtn")
        self.trainBtn = QtWidgets.QPushButton(self.groupBox)
        self.trainBtn.setEnabled(True)
        self.trainBtn.setGeometry(QtCore.QRect(250, 400, 280, 70))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.trainBtn.setFont(font)
        self.trainBtn.setAcceptDrops(False)
        self.trainBtn.setAutoFillBackground(False)
        self.trainBtn.setStyleSheet("background-color: rgb(100, 104, 108);\n"
"font: 75 14pt \"Sitka Small\";\n"
"color: rgb(0, 0, 0);\n"
"border-width: 3px;\n"
"border-radius: 30px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style: solid;")
        self.trainBtn.setCheckable(False)
        self.trainBtn.setAutoDefault(False)
        self.trainBtn.setDefault(False)
        self.trainBtn.setFlat(False)
        self.trainBtn.setObjectName("trainBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fake Texts Detector"))
        self.groupBox.setTitle(_translate("MainWindow", "Fake Texts Detector"))
        self.plagiarismBtn.setText(_translate("MainWindow", "Plagiarism"))
        self.fakeNewsBtn.setText(_translate("MainWindow", "Fake News"))
        self.trainBtn.setText(_translate("MainWindow", "Train Model"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
