# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'train_progress_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrainProgressWindow(object):
    def setupUi(self, TrainProgressWindow):
        TrainProgressWindow.setObjectName("TrainProgressWindow")
        TrainProgressWindow.resize(860, 598)
        self.centralwidget = QtWidgets.QWidget(TrainProgressWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundImg = QtWidgets.QLabel(self.centralwidget)
        self.backgroundImg.setGeometry(QtCore.QRect(0, 0, 860, 600))
        self.backgroundImg.setText("")
        self.backgroundImg.setPixmap(QtGui.QPixmap("../../RESOURCES/background.jpg"))
        self.backgroundImg.setScaledContents(True)
        self.backgroundImg.setObjectName("backgroundImg")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(30, 0, 800, 570))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.resultsBtn = QtWidgets.QPushButton(self.groupBox)
        self.resultsBtn.setEnabled(False)
        self.resultsBtn.setGeometry(QtCore.QRect(530, 479, 240, 60))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.resultsBtn.setFont(font)
        self.resultsBtn.setAcceptDrops(False)
        self.resultsBtn.setAutoFillBackground(False)
        self.resultsBtn.setStyleSheet("background-color: rgb(0, 111, 0);\n"
                                      "\n"
                                      "font: 75 16pt \"Sitka Small\";\n"
                                      "color: rgb(255, 255, 255);\n"
                                      "border-width: 3px;\n"
                                      "border-radius: 30px;\n"
                                      "border-color: rgb(255, 255, 255);\n"
                                      "border-style: solid;\n"
                                      "\n"
                                      "alternate-background-color: rgb(135, 135, 135);")
        self.resultsBtn.setCheckable(False)
        self.resultsBtn.setAutoDefault(False)
        self.resultsBtn.setDefault(False)
        self.resultsBtn.setFlat(False)
        self.resultsBtn.setObjectName("resultsBtn")
        self.cancelBtn = QtWidgets.QPushButton(self.groupBox)
        self.cancelBtn.setEnabled(True)
        self.cancelBtn.setGeometry(QtCore.QRect(30, 479, 240, 60))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.cancelBtn.setFont(font)
        self.cancelBtn.setAcceptDrops(False)
        self.cancelBtn.setAutoFillBackground(False)
        self.cancelBtn.setStyleSheet("\n"
                                     "background-color: rgb(159, 0, 0);\n"
                                     "font: 75 16pt \"Sitka Small\";\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "border-width: 3px;\n"
                                     "border-radius: 30px;\n"
                                     "border-color: rgb(255, 255, 255);\n"
                                     "border-style: solid;")
        self.cancelBtn.setIconSize(QtCore.QSize(24, 24))
        self.cancelBtn.setCheckable(False)
        self.cancelBtn.setAutoDefault(False)
        self.cancelBtn.setDefault(False)
        self.cancelBtn.setFlat(False)
        self.cancelBtn.setObjectName("cancelBtn")
        self.verticalFrame = QtWidgets.QFrame(self.groupBox)
        self.verticalFrame.setGeometry(QtCore.QRect(100, 230, 600, 100))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.verticalFrame.setFont(font)
        self.verticalFrame.setAutoFillBackground(False)
        self.verticalFrame.setStyleSheet("border-width: 4px;\n"
                                         "border-radius: 15px;\n"
                                         "border-color: rgb(0, 0, 0);\n"
                                         "border-style: solid;\n"
                                         "font: 10pt \"Sitka Small\";\n"
                                         "color: rgb(255, 255, 255);\n"
                                         "background-color: qlineargradient(spread:pad, x1:0.996, y1:0.0340909, x2:1, y2:0, stop:1 rgba(0, 0, 32, 170));")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(10, 0, 10, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.verticalFrame)
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setStyleSheet("background-color: rgb(230, 230, 230);\n"
                                       "color: rgb(0, 0, 94);\n"
                                       "border-width: 2px;\n"
                                       "border-radius: 3px;")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        TrainProgressWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TrainProgressWindow)
        QtCore.QMetaObject.connectSlotsByName(TrainProgressWindow)

    def retranslateUi(self, TrainProgressWindow):
        _translate = QtCore.QCoreApplication.translate
        TrainProgressWindow.setWindowTitle(_translate("TrainProgressWindow", "Train Model Progress"))
        self.groupBox.setTitle(_translate("TrainProgressWindow", "Train Progress"))
        self.resultsBtn.setText(_translate("TrainProgressWindow", "Results"))
        self.cancelBtn.setText(_translate("TrainProgressWindow", "Cancel"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    TrainProgressWindow = QtWidgets.QMainWindow()
    ui = Ui_TrainProgressWindow()
    ui.setupUi(TrainProgressWindow)
    TrainProgressWindow.show()
    sys.exit(app.exec_())
