# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'train_news_model_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrainNewsModelWindow(object):
    def setupUi(self, TrainNewsModelWindow):
        TrainNewsModelWindow.setObjectName("TrainNewsModelWindow")
        TrainNewsModelWindow.resize(860, 598)
        self.centralwidget = QtWidgets.QWidget(TrainNewsModelWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.backgroundImg = QtWidgets.QLabel(self.centralwidget)
        self.backgroundImg.setGeometry(QtCore.QRect(0, 0, 860, 600))
        self.backgroundImg.setText("")
        self.backgroundImg.setPixmap(QtGui.QPixmap("../../RESOURCES/background.jpg"))
        self.backgroundImg.setScaledContents(True)
        self.backgroundImg.setObjectName("backgroundImg")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(30, 0, 800, 570))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.groupBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Sitka Heading")
        font.setPointSize(36)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"                    ")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.trainBtn = QtWidgets.QPushButton(self.groupBox)
        self.trainBtn.setEnabled(True)
        self.trainBtn.setGeometry(QtCore.QRect(530, 479, 240, 60))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.trainBtn.setFont(font)
        self.trainBtn.setAcceptDrops(False)
        self.trainBtn.setAutoFillBackground(False)
        self.trainBtn.setStyleSheet("\n"
"                            background-color: rgb(0, 0, 20);\n"
"                            font: 75 16pt \"Sitka Small\";\n"
"                            color: rgb(255, 255, 255);\n"
"                            border-width: 3px;\n"
"                            border-radius: 30px;\n"
"                            border-color: rgb(255, 255, 255);\n"
"                            border-style: solid;\n"
"                        ")
        self.trainBtn.setCheckable(False)
        self.trainBtn.setAutoDefault(False)
        self.trainBtn.setDefault(False)
        self.trainBtn.setFlat(False)
        self.trainBtn.setObjectName("trainBtn")
        self.backBtn = QtWidgets.QPushButton(self.groupBox)
        self.backBtn.setEnabled(True)
        self.backBtn.setGeometry(QtCore.QRect(30, 479, 240, 60))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.backBtn.setFont(font)
        self.backBtn.setAcceptDrops(False)
        self.backBtn.setAutoFillBackground(False)
        self.backBtn.setStyleSheet("\n"
"                            background-color: rgb(159, 0, 0);\n"
"                            font: 75 16pt \"Sitka Small\";\n"
"                            color: rgb(255, 255, 255);\n"
"                            border-width: 3px;\n"
"                            border-radius: 30px;\n"
"                            border-color: rgb(255, 255, 255);\n"
"                            border-style: solid;\n"
"                        ")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/My Documents/Studies/Semester_9/פרויקט מסכם - שלב\n"
"                                ב/icons/pnghut_arrow-icon-direction-left-logo-text.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backBtn.setIcon(icon)
        self.backBtn.setIconSize(QtCore.QSize(24, 24))
        self.backBtn.setCheckable(False)
        self.backBtn.setAutoDefault(False)
        self.backBtn.setDefault(False)
        self.backBtn.setFlat(False)
        self.backBtn.setObjectName("backBtn")
        self.verticalFrame1 = QtWidgets.QFrame(self.groupBox)
        self.verticalFrame1.setGeometry(QtCore.QRect(420, 100, 370, 320))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.verticalFrame1.setFont(font)
        self.verticalFrame1.setAutoFillBackground(False)
        self.verticalFrame1.setStyleSheet("border-width: 3px;\n"
"                            border-radius: 15px;\n"
"                            border-color: rgb(0, 0, 0);\n"
"                            border-style: solid;\n"
"                            font: 8pt \"Sitka Small\";\n"
"                            color: rgb(255, 255, 255);\n"
"                            background-color: qlineargradient(spread:pad, x1:0.996, y1:0.0340909, x2:1, y2:0, stop:1\n"
"                            rgba(0, 0, 32, 170));\n"
"                        ")
        self.verticalFrame1.setObjectName("verticalFrame1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame1)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalGroupBox11 = QtWidgets.QGroupBox(self.verticalFrame1)
        self.verticalGroupBox11.setStyleSheet("border-width: 2px;\n"
"font: 10pt \"Sitka Small\";")
        self.verticalGroupBox11.setObjectName("verticalGroupBox11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalGroupBox11)
        self.verticalLayout_6.setContentsMargins(5, 36, 5, 18)
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label114 = QtWidgets.QLabel(self.verticalGroupBox11)
        self.label114.setStyleSheet("border-width: 0px;\n"
"font: 8pt \"Sitka Small\";")
        self.label114.setObjectName("label114")
        self.verticalLayout_6.addWidget(self.label114)
        self.horizontalLayout111 = QtWidgets.QHBoxLayout()
        self.horizontalLayout111.setObjectName("horizontalLayout111")
        self.inputPath1111 = QtWidgets.QLineEdit(self.verticalGroupBox11)
        self.inputPath1111.setStyleSheet("border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                            background-color: rgb(188, 188, 188);\n"
"                                                            color: rgb(0, 0, 0);\n"
"                                                        ")
        self.inputPath1111.setReadOnly(True)
        self.inputPath1111.setObjectName("inputPath1111")
        self.horizontalLayout111.addWidget(self.inputPath1111)
        self.uploadBtn1112 = QtWidgets.QToolButton(self.verticalGroupBox11)
        self.uploadBtn1112.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadBtn1112.setMouseTracking(False)
        self.uploadBtn1112.setAutoFillBackground(False)
        self.uploadBtn1112.setStyleSheet("background-color: rgb(212, 212, 212);\n"
"                                                            border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                        ")
        self.uploadBtn1112.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../RESOURCES/upload_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uploadBtn1112.setIcon(icon1)
        self.uploadBtn1112.setObjectName("uploadBtn1112")
        self.horizontalLayout111.addWidget(self.uploadBtn1112)
        self.verticalLayout_6.addLayout(self.horizontalLayout111)
        self.label115 = QtWidgets.QLabel(self.verticalGroupBox11)
        self.label115.setStyleSheet("border-width: 0px;\n"
"font: 8pt \"Sitka Small\";")
        self.label115.setObjectName("label115")
        self.verticalLayout_6.addWidget(self.label115)
        self.horizontalLayout112 = QtWidgets.QHBoxLayout()
        self.horizontalLayout112.setObjectName("horizontalLayout112")
        self.inputPath1121 = QtWidgets.QLineEdit(self.verticalGroupBox11)
        self.inputPath1121.setStyleSheet("border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                            background-color: rgb(188, 188, 188);\n"
"                                                            color: rgb(0, 0, 0);\n"
"                                                        ")
        self.inputPath1121.setReadOnly(True)
        self.inputPath1121.setObjectName("inputPath1121")
        self.horizontalLayout112.addWidget(self.inputPath1121)
        self.uploadBtn1122 = QtWidgets.QToolButton(self.verticalGroupBox11)
        self.uploadBtn1122.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadBtn1122.setMouseTracking(False)
        self.uploadBtn1122.setAutoFillBackground(False)
        self.uploadBtn1122.setStyleSheet("background-color: rgb(212, 212, 212);\n"
"                                                            border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                        ")
        self.uploadBtn1122.setText("")
        self.uploadBtn1122.setIcon(icon1)
        self.uploadBtn1122.setObjectName("uploadBtn1122")
        self.horizontalLayout112.addWidget(self.uploadBtn1122)
        self.verticalLayout_6.addLayout(self.horizontalLayout112)
        self.label116 = QtWidgets.QLabel(self.verticalGroupBox11)
        self.label116.setStyleSheet("border-width: 0px;\n"
"font: 8pt \"Sitka Small\";")
        self.label116.setObjectName("label116")
        self.verticalLayout_6.addWidget(self.label116)
        self.inputTextColumnName113 = QtWidgets.QLineEdit(self.verticalGroupBox11)
        self.inputTextColumnName113.setEnabled(True)
        self.inputTextColumnName113.setAutoFillBackground(False)
        self.inputTextColumnName113.setStyleSheet("border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                            background-color: rgb(188, 188, 188);\n"
"                                                            color: rgb(0, 0, 0);\n"
"                                                        \n"
"")
        self.inputTextColumnName113.setObjectName("inputTextColumnName113")
        self.verticalLayout_6.addWidget(self.inputTextColumnName113)
        self.verticalLayout.addWidget(self.verticalGroupBox11)
        self.verticalGroupBox12 = QtWidgets.QGroupBox(self.verticalFrame1)
        self.verticalGroupBox12.setStyleSheet("border-width: 2px;\n"
"font: 10pt \"Sitka Small\";")
        self.verticalGroupBox12.setObjectName("verticalGroupBox12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalGroupBox12)
        self.verticalLayout_5.setContentsMargins(5, 36, 5, 18)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout121 = QtWidgets.QHBoxLayout()
        self.horizontalLayout121.setObjectName("horizontalLayout121")
        self.inputPath1211 = QtWidgets.QLineEdit(self.verticalGroupBox12)
        self.inputPath1211.setStyleSheet("border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                            background-color: rgb(188, 188, 188);\n"
"                                                            color: rgb(0, 0, 0);\n"
"                                                        ")
        self.inputPath1211.setReadOnly(True)
        self.inputPath1211.setObjectName("inputPath1211")
        self.horizontalLayout121.addWidget(self.inputPath1211)
        self.uploadBtn1212 = QtWidgets.QToolButton(self.verticalGroupBox12)
        self.uploadBtn1212.setMinimumSize(QtCore.QSize(0, 0))
        self.uploadBtn1212.setMouseTracking(False)
        self.uploadBtn1212.setAutoFillBackground(False)
        self.uploadBtn1212.setStyleSheet("background-color: rgb(212, 212, 212);\n"
"                                                            border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                        ")
        self.uploadBtn1212.setText("")
        self.uploadBtn1212.setIcon(icon1)
        self.uploadBtn1212.setObjectName("uploadBtn1212")
        self.horizontalLayout121.addWidget(self.uploadBtn1212)
        self.verticalLayout_5.addLayout(self.horizontalLayout121)
        self.text126 = QtWidgets.QLabel(self.verticalGroupBox12)
        self.text126.setStyleSheet("border-width: 0px;\n"
"font: 8pt \"Sitka Small\";")
        self.text126.setObjectName("text126")
        self.verticalLayout_5.addWidget(self.text126)
        self.horizontalLayout122 = QtWidgets.QHBoxLayout()
        self.horizontalLayout122.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout122.setObjectName("horizontalLayout122")
        self.inputTextColumnName1221 = QtWidgets.QLineEdit(self.verticalGroupBox12)
        self.inputTextColumnName1221.setStyleSheet("border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                            background-color: rgb(188, 188, 188);\n"
"                                                            color: rgb(0, 0, 0);\n"
"                                                        ")
        self.inputTextColumnName1221.setObjectName("inputTextColumnName1221")
        self.horizontalLayout122.addWidget(self.inputTextColumnName1221)
        self.questionBtn1222 = QtWidgets.QToolButton(self.verticalGroupBox12)
        self.questionBtn1222.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn1222.setMouseTracking(False)
        self.questionBtn1222.setAutoFillBackground(False)
        self.questionBtn1222.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"                                                            background-color: rgb(0, 0, 50);\n"
"                                                            border-width: 1px;\n"
"                                                            border-radius: 14px;\n"
"                                                            border-color: rgb(255, 255, 255);\n"
"                                                            border-style: solid;\n"
"                                                        ")
        self.questionBtn1222.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../RESOURCES/question_icon2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.questionBtn1222.setIcon(icon2)
        self.questionBtn1222.setObjectName("questionBtn1222")
        self.horizontalLayout122.addWidget(self.questionBtn1222)
        self.verticalLayout_5.addLayout(self.horizontalLayout122)
        self.label127 = QtWidgets.QLabel(self.verticalGroupBox12)
        self.label127.setStyleSheet("border-width: 0px;\n"
"font: 8pt \"Sitka Small\";")
        self.label127.setObjectName("label127")
        self.verticalLayout_5.addWidget(self.label127)
        self.horizontalLayout123 = QtWidgets.QHBoxLayout()
        self.horizontalLayout123.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout123.setObjectName("horizontalLayout123")
        self.inputLabelColumnName1231 = QtWidgets.QLineEdit(self.verticalGroupBox12)
        self.inputLabelColumnName1231.setStyleSheet("border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                            background-color: rgb(188, 188, 188);\n"
"                                                            color: rgb(0, 0, 0);\n"
"                                                        ")
        self.inputLabelColumnName1231.setObjectName("inputLabelColumnName1231")
        self.horizontalLayout123.addWidget(self.inputLabelColumnName1231)
        self.questionBtn1232 = QtWidgets.QToolButton(self.verticalGroupBox12)
        self.questionBtn1232.setMinimumSize(QtCore.QSize(0, 0))
        self.questionBtn1232.setMouseTracking(False)
        self.questionBtn1232.setAutoFillBackground(False)
        self.questionBtn1232.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"                                                            background-color: rgb(0, 0, 50);\n"
"                                                            border-width: 1px;\n"
"                                                            border-radius: 14px;\n"
"                                                            border-color: rgb(255, 255, 255);\n"
"                                                            border-style: solid;\n"
"                                                        ")
        self.questionBtn1232.setText("")
        self.questionBtn1232.setIcon(icon2)
        self.questionBtn1232.setObjectName("questionBtn1232")
        self.horizontalLayout123.addWidget(self.questionBtn1232)
        self.verticalLayout_5.addLayout(self.horizontalLayout123)
        self.horizontalLayout124 = QtWidgets.QHBoxLayout()
        self.horizontalLayout124.setContentsMargins(-1, 0, 40, 0)
        self.horizontalLayout124.setSpacing(14)
        self.horizontalLayout124.setObjectName("horizontalLayout124")
        self.label1241 = QtWidgets.QLabel(self.verticalGroupBox12)
        self.label1241.setStyleSheet("border-width: 0px;\n"
"font: 8pt \"Sitka Small\";\n"
"")
        self.label1241.setObjectName("label1241")
        self.horizontalLayout124.addWidget(self.label1241)
        self.inputRealLabel1242 = QtWidgets.QLineEdit(self.verticalGroupBox12)
        self.inputRealLabel1242.setStyleSheet("border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                            background-color: rgb(188, 188, 188);\n"
"                                                            color: rgb(0, 0, 0);\n"
"                                                        ")
        self.inputRealLabel1242.setAlignment(QtCore.Qt.AlignCenter)
        self.inputRealLabel1242.setObjectName("inputRealLabel1242")
        self.horizontalLayout124.addWidget(self.inputRealLabel1242)
        self.verticalLayout_5.addLayout(self.horizontalLayout124)
        self.horizontalLayout125 = QtWidgets.QHBoxLayout()
        self.horizontalLayout125.setContentsMargins(0, -1, 40, -1)
        self.horizontalLayout125.setSpacing(11)
        self.horizontalLayout125.setObjectName("horizontalLayout125")
        self.label1251 = QtWidgets.QLabel(self.verticalGroupBox12)
        self.label1251.setStyleSheet("border-width: 0px;\n"
"font: 8pt \"Sitka Small\";")
        self.label1251.setObjectName("label1251")
        self.horizontalLayout125.addWidget(self.label1251)
        self.inputFakeLabel1252 = QtWidgets.QLineEdit(self.verticalGroupBox12)
        self.inputFakeLabel1252.setStyleSheet("border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                            background-color: rgb(188, 188, 188);\n"
"                                                            color: rgb(0, 0, 0);\n"
"                                                        \n"
"")
        self.inputFakeLabel1252.setAlignment(QtCore.Qt.AlignCenter)
        self.inputFakeLabel1252.setDragEnabled(False)
        self.inputFakeLabel1252.setObjectName("inputFakeLabel1252")
        self.horizontalLayout125.addWidget(self.inputFakeLabel1252)
        self.verticalLayout_5.addLayout(self.horizontalLayout125)
        self.verticalLayout.addWidget(self.verticalGroupBox12)
        self.errorMsg = QtWidgets.QLabel(self.groupBox)
        self.errorMsg.setGeometry(QtCore.QRect(280, 430, 81, 41))
        self.errorMsg.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.errorMsg.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.983, y1:0.00568182,\n"
"                            x2:0.996, y2:0, stop:1 rgba(48, 48, 48, 143));\n"
"                            color: rgb(170, 0, 0);\n"
"                            font: 75 8pt \"System\";\n"
"                            border-radius: 10px;\n"
"                            border-style: solid;\n"
"                            border-width: 0px\n"
"                        ")
        self.errorMsg.setObjectName("errorMsg")
        self.verticalFrame2 = QtWidgets.QFrame(self.groupBox)
        self.verticalFrame2.setGeometry(QtCore.QRect(10, 100, 400, 180))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.verticalFrame2.setFont(font)
        self.verticalFrame2.setAutoFillBackground(False)
        self.verticalFrame2.setStyleSheet("border-width: 3px;\n"
"                            border-radius: 15px;\n"
"                            border-color: rgb(0, 0, 0);\n"
"                            border-style: solid;\n"
"                            font: 8pt \"Sitka Small\";\n"
"                            color: rgb(255, 255, 255);\n"
"                            background-color: qlineargradient(spread:pad, x1:0.996, y1:0.0340909, x2:1, y2:0, stop:1\n"
"                            rgba(0, 0, 32, 170));\n"
"                        ")
        self.verticalFrame2.setObjectName("verticalFrame2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalFrame2)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalGroupBox21 = QtWidgets.QGroupBox(self.verticalFrame2)
        self.verticalGroupBox21.setObjectName("verticalGroupBox21")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox21)
        self.verticalLayout_2.setContentsMargins(5, 36, 5, 18)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout211 = QtWidgets.QHBoxLayout()
        self.horizontalLayout211.setObjectName("horizontalLayout211")
        self.radioButton2111 = QtWidgets.QRadioButton(self.verticalGroupBox21)
        self.radioButton2111.setAutoFillBackground(False)
        self.radioButton2111.setChecked(True)
        self.radioButton2111.setObjectName("radioButton2111")
        self.horizontalLayout211.addWidget(self.radioButton2111)
        self.verticalLayout_2.addLayout(self.horizontalLayout211)
        self.horizontalLayout212 = QtWidgets.QHBoxLayout()
        self.horizontalLayout212.setObjectName("horizontalLayout212")
        self.radioButton2121 = QtWidgets.QRadioButton(self.verticalGroupBox21)
        self.radioButton2121.setObjectName("radioButton2121")
        self.horizontalLayout212.addWidget(self.radioButton2121)
        self.verticalLayout_2.addLayout(self.horizontalLayout212)
        self.verticalLayout_3.addWidget(self.verticalGroupBox21)
        self.verticalFrame3 = QtWidgets.QFrame(self.groupBox)
        self.verticalFrame3.setGeometry(QtCore.QRect(10, 290, 400, 130))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.verticalFrame3.setFont(font)
        self.verticalFrame3.setAutoFillBackground(False)
        self.verticalFrame3.setStyleSheet("border-width: 3px;\n"
"                            border-radius: 15px;\n"
"                            border-color: rgb(0, 0, 0);\n"
"                            border-style: solid;\n"
"                            font: 8pt \"Sitka Small\";\n"
"                            color: rgb(255, 255, 255);\n"
"                            background-color: qlineargradient(spread:pad, x1:0.996, y1:0.0340909, x2:1, y2:0, stop:1\n"
"                            rgba(0, 0, 32, 170));\n"
"                        ")
        self.verticalFrame3.setObjectName("verticalFrame3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalFrame3)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalGroupBox31 = QtWidgets.QGroupBox(self.verticalFrame3)
        self.verticalGroupBox31.setStyleSheet("border-width: 2px;\n"
"font: 8pt \"Sitka Small\";")
        self.verticalGroupBox31.setObjectName("verticalGroupBox31")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalGroupBox31)
        self.verticalLayout_7.setContentsMargins(5, 36, 5, 18)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout311 = QtWidgets.QHBoxLayout()
        self.horizontalLayout311.setObjectName("horizontalLayout311")
        self.label3111 = QtWidgets.QLabel(self.verticalGroupBox31)
        self.label3111.setStyleSheet("border-width: 0px;\n"
"")
        self.label3111.setObjectName("label3111")
        self.horizontalLayout311.addWidget(self.label3111)
        self.inputEpoch3112 = QtWidgets.QLineEdit(self.verticalGroupBox31)
        self.inputEpoch3112.setStyleSheet("border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                            background-color: rgb(188, 188, 188);\n"
"                                                            color: rgb(0, 0, 0);\n"
"                                                        ")
        self.inputEpoch3112.setObjectName("inputEpoch3112")
        self.horizontalLayout311.addWidget(self.inputEpoch3112)
        self.label3113 = QtWidgets.QLabel(self.verticalGroupBox31)
        self.label3113.setStyleSheet("border-width: 0px;\n"
"")
        self.label3113.setObjectName("label3113")
        self.horizontalLayout311.addWidget(self.label3113)
        self.inputBatchSz3114 = QtWidgets.QLineEdit(self.verticalGroupBox31)
        self.inputBatchSz3114.setStyleSheet("border-width: 3px;\n"
"                                                            border-radius: 5px;\n"
"                                                            border-color: rgb(0, 0, 0);\n"
"                                                            border-style: solid;\n"
"                                                            background-color: rgb(188, 188, 188);\n"
"                                                            color: rgb(0, 0, 0);\n"
"                                                        ")
        self.inputBatchSz3114.setObjectName("inputBatchSz3114")
        self.horizontalLayout311.addWidget(self.inputBatchSz3114)
        self.verticalLayout_7.addLayout(self.horizontalLayout311)
        self.verticalLayout_4.addWidget(self.verticalGroupBox31)
        TrainNewsModelWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(TrainNewsModelWindow)
        QtCore.QMetaObject.connectSlotsByName(TrainNewsModelWindow)

    def retranslateUi(self, TrainNewsModelWindow):
        _translate = QtCore.QCoreApplication.translate
        TrainNewsModelWindow.setWindowTitle(_translate("TrainNewsModelWindow", "Train Fake News Model"))
        self.groupBox.setTitle(_translate("TrainNewsModelWindow", "Train a new Model"))
        self.trainBtn.setText(_translate("TrainNewsModelWindow", "Train"))
        self.backBtn.setText(_translate("TrainNewsModelWindow", "Back"))
        self.verticalGroupBox11.setTitle(_translate("TrainNewsModelWindow", "Upload two SCV files:"))
        self.label114.setText(_translate("TrainNewsModelWindow", "Real news file path:"))
        self.inputPath1111.setText(_translate("TrainNewsModelWindow", "C:/Users/Vladplat/PycharmProjects/Fake-News-And-Authorship-Detection/DATABASE/fakenews/db1/true5.csv"))
        self.label115.setText(_translate("TrainNewsModelWindow", "Fake news file path:"))
        self.inputPath1121.setText(_translate("TrainNewsModelWindow", "C:/Users/Vladplat/PycharmProjects/Fake-News-And-Authorship-Detection/DATABASE/fakenews/db1/fake5.csv"))
        self.label116.setText(_translate("TrainNewsModelWindow", "Text\'s column name:"))
        self.inputTextColumnName113.setText(_translate("TrainNewsModelWindow", "text"))
        self.verticalGroupBox12.setTitle(_translate("TrainNewsModelWindow", "Upload CSV file:"))
        self.text126.setText(_translate("TrainNewsModelWindow", "Text\'s column name:"))
        self.label127.setText(_translate("TrainNewsModelWindow", "Label\'s column name:"))
        self.label1241.setText(_translate("TrainNewsModelWindow", "Label for real news: "))
        self.label1251.setText(_translate("TrainNewsModelWindow", "Label for fake news: "))
        self.errorMsg.setText(_translate("TrainNewsModelWindow", "warning"))
        self.verticalGroupBox21.setTitle(_translate("TrainNewsModelWindow", "Choose a relevant format of your DB:"))
        self.radioButton2111.setText(_translate("TrainNewsModelWindow", "CSV File with column for label"))
        self.radioButton2121.setText(_translate("TrainNewsModelWindow", "Two seperated SCV files for each label"))
        self.verticalGroupBox31.setTitle(_translate("TrainNewsModelWindow", "Training Hyperparameters:"))
        self.label3111.setText(_translate("TrainNewsModelWindow", "Epoch:"))
        self.inputEpoch3112.setText(_translate("TrainNewsModelWindow", "2"))
        self.inputEpoch3112.setPlaceholderText(_translate("TrainNewsModelWindow", "15"))
        self.label3113.setText(_translate("TrainNewsModelWindow", "Batch size:"))
        self.inputBatchSz3114.setText(_translate("TrainNewsModelWindow", "2"))
        self.inputBatchSz3114.setPlaceholderText(_translate("TrainNewsModelWindow", "10"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TrainNewsModelWindow = QtWidgets.QMainWindow()
    ui = Ui_TrainNewsModelWindow()
    ui.setupUi(TrainNewsModelWindow)
    TrainNewsModelWindow.show()
    sys.exit(app.exec_())
